import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ru' | 'ro' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.services': 'Услуги',
    'nav.portfolio': 'Портфолио',
    'nav.blog': 'Блог',
    'nav.contact': 'Контакты',
    
    // Hero
    'hero.title': 'Создаём сайты, которые',
    'hero.highlight': 'продают',
    'hero.subtitle': 'Профессиональная разработка сайтов в Молдове. Лендинги, интернет-магазины и корпоративные сайты под ключ с гарантией результата.',
    'hero.cta': 'Оставить заявку',
    'hero.consultation': 'Бесплатная консультация',
    
    // About
    'about.title': 'О нас',
    'about.subtitle': 'WebPoint — это команда профессионалов, которая создаёт современные веб-решения для вашего бизнеса',
    'about.experience': 'Лет опыта',
    'about.projects': 'Проектов',
    'about.clients': 'Довольных клиентов',
    
    // Services
    'services.title': 'Наши услуги',
    'services.subtitle': 'Выберите подходящее решение для вашего бизнеса',
    'services.landing': 'Лендинг',
    'services.landing.desc': 'Продающая одностраничная страница для привлечения клиентов и увеличения конверсии',
    'services.business': 'Сайт-визитка',
    'services.business.desc': 'Многостраничный корпоративный сайт с полной информацией о вашей компании',
    'services.shop': 'Интернет-магазин',
    'services.shop.desc': 'Полнофункциональный онлайн-магазин с каталогом, корзиной и системой оплаты',
    'services.from': 'от',
    'services.order': 'Заказать',
    'services.time.landing': '7-10 дней',
    'services.time.business': '14-21 день',
    'services.time.shop': '30-45 дней',
    'services.duration': 'Срок',
    'services.features.landing.design': 'Современный дизайн',
    'services.features.landing.responsive': 'Адаптивная верстка',
    'services.features.landing.seo': 'SEO-оптимизация',
    'services.features.landing.form': 'Форма заявки',
    'services.features.business.pages': 'До 10 страниц',
    'services.features.business.cms': 'CMS админ-панель',
    'services.features.business.social': 'Интеграция с соцсетями',
    'services.features.business.analytics': 'Аналитика',
    'services.features.shop.catalog': 'Каталог товаров',
    'services.features.shop.cart': 'Корзина и оплата',
    'services.features.shop.account': 'Личный кабинет',
    'services.features.shop.delivery': 'Интеграция доставки',
    'services.features.landing.full.design': 'Уникальный современный дизайн',
    'services.features.landing.full.responsive': 'Адаптивная верстка для всех устройств',
    'services.features.landing.full.seo': 'SEO-оптимизация и настройка метатегов',
    'services.features.landing.full.form': 'Форма заявки с email-уведомлениями',
    'services.features.landing.full.analytics': 'Интеграция с Google Analytics',
    'services.features.landing.full.hosting': 'Настройка хостинга и домена',
    'services.features.landing.full.support': 'Месяц технической поддержки',
    'services.features.landing.full.training': 'Обучение по управлению контентом',
    'services.features.business.full.pages': 'До 10 информационных страниц',
    'services.features.business.full.design': 'Уникальный дизайн под ваш бренд',
    'services.features.business.full.cms': 'Административная панель (CMS)',
    'services.features.business.full.contact': 'Форма обратной связи',
    'services.features.business.full.social': 'Интеграция с социальными сетями',
    'services.features.business.full.blog': 'Блог или новостной раздел',
    'services.features.business.full.multilang': 'Мультиязычность (RU/RO)',
    'services.features.business.full.maps': 'Google Maps интеграция',
    'services.features.business.full.seo': 'SEO-оптимизация всех страниц',
    'services.features.business.full.support': '3 месяца технической поддержки',
    'services.features.shop.full.catalog': 'Каталог товаров с фильтрацией',
    'services.features.shop.full.cart': 'Корзина и оформление заказа',
    'services.features.shop.full.payment': 'Интеграция платежных систем',
    'services.features.shop.full.account': 'Личный кабинет клиента',
    'services.features.shop.full.admin': 'Административная панель управления',
    'services.features.shop.full.discounts': 'Система скидок и промокодов',
    'services.features.shop.full.delivery': 'Интеграция служб доставки',
    'services.features.shop.full.notifications': 'Email-уведомления о заказах',
    'services.features.shop.full.reviews': 'Отзывы и рейтинг товаров',
    'services.features.shop.full.multilang': 'Мультиязычность и мультивалютность',
    'services.features.shop.full.seo': 'SEO-оптимизация товаров',
    'services.features.shop.full.support': '6 месяцев технической поддержки',
    'services.additional.support.title': 'Поддержка и развитие',
    'services.additional.support.price': '€50/мес',
    'services.additional.support.content': 'Обновление контента',
    'services.additional.support.tech': 'Техническая поддержка',
    'services.additional.support.monitoring': 'Мониторинг безопасности',
    'services.additional.seo.title': 'SEO-продвижение',
    'services.additional.seo.price': '€200/мес',
    'services.additional.seo.analysis': 'Анализ конкурентов',
    'services.additional.seo.optimization': 'Оптимизация контента',
    'services.additional.seo.links': 'Работа со ссылками',
    'services.additional.ads.title': 'Контекстная реклама',
    'services.additional.ads.price': '€150/мес',
    'services.additional.ads.google': 'Настройка Google Ads',
    'services.additional.ads.facebook': 'Facebook Ads',
    'services.additional.ads.analytics': 'Аналитика и отчеты',
    'services.additional.more': 'Узнать подробнее',
    'services.additional.title': 'Дополнительные услуги',
    'services.additional.subtitle': 'Расширьте возможности вашего сайта',
    'services.cta.title': 'Не нашли подходящий пакет?',
    'services.cta.subtitle': 'Мы создадим индивидуальное предложение под ваши задачи и бюджет',
    'services.cta.button': 'Получить консультацию',
    
    // Features
    'features.design': 'Современный дизайн',
    'features.design.desc': 'Уникальный дизайн, адаптированный под ваш бренд',
    'features.responsive': 'Адаптивная вёрстка',
    'features.responsive.desc': 'Корректное отображение на всех устройствах',
    'features.seo': 'SEO-оптимизация',
    'features.seo.desc': 'Настройка для поисковых систем и быстрой индексации',
    'features.support': 'Техподдержка',
    'features.support.desc': 'Гарантийная поддержка и обслуживание сайта',
    
    // Portfolio
    'portfolio.title': 'Наши работы',
    'portfolio.subtitle': 'Примеры успешно реализованных проектов',
    'portfolio.all': 'Все',
    'portfolio.landing': 'Лендинги',
    'portfolio.business': 'Сайты-визитки',
    'portfolio.shop': 'Магазины',
    'portfolio.problem': 'Проблема',
    'portfolio.solution': 'Решение',
    'portfolio.result': 'Результат',
    'portfolio.view': 'Посмотреть проект',
    'portfolio.back': 'Вернуться к портфолио',
    
    // Blog
    'blog.title': 'Блог',
    'blog.subtitle': 'Полезные статьи о создании и продвижении сайтов',
    'blog.readMore': 'Читать далее',
    'blog.readTime': 'мин чтения',
    'blog.back': 'Вернуться к блогу',
    
    // Contact
    'contact.title': 'Свяжитесь с нами',
    'contact.subtitle': 'Готовы обсудить ваш проект? Оставьте заявку, и мы свяжемся с вами в ближайшее время',
    'contact.name': 'Ваше имя',
    'contact.email': 'Email',
    'contact.phone': 'Телефон',
    'contact.message': 'Сообщение',
    'contact.projectType': 'Тип проекта',
    'contact.send': 'Отправить заявку',
    'contact.sending': 'Отправка...',
    'contact.success': 'Спасибо! Мы свяжемся с вами в ближайшее время.',
    'contact.error': 'Произошла ошибка. Попробуйте позже.',
    'contact.phone.label': 'Телефон',
    'contact.email.label': 'Email',
    'contact.address.label': 'Адрес',
    'contact.address.value': 'Кишинёв, ул. Пушкина 22',
    'contact.quick.title': 'Быстрая связь',
    'contact.quick.write': 'Написать сообщение',
    'contact.hours.title': 'Время работы',
    'contact.hours.weekdays': 'Пн - Пт',
    'contact.hours.weekdays.time': '09:00 - 18:00',
    'contact.hours.saturday': 'Суббота',
    'contact.hours.saturday.time': '10:00 - 15:00',
    'contact.hours.sunday': 'Воскресенье',
    'contact.hours.sunday.time': 'Выходной',
    'contact.faq.title': 'Часто задаваемые вопросы',
    'contact.faq.q1': 'Как долго создаётся сайт?',
    'contact.faq.a1': 'Лендинг - 7-10 дней, сайт-визитка - 14-21 день, интернет-магазин - 30-45 дней.',
    'contact.faq.q2': 'Какая форма оплаты?',
    'contact.faq.a2': 'Предоплата 50% для начала работ, 50% после сдачи проекта. Возможна рассрочка.',
    'contact.faq.q3': 'Включена ли техподдержка?',
    'contact.faq.a3': 'Да, гарантийная поддержка от 1 до 6 месяцев в зависимости от пакета.',
    'contact.faq.q4': 'Можно ли самому редактировать контент?',
    'contact.faq.a4': 'Да, мы предоставляем CMS-панель и обучаем работе с ней.',
    'contact.form.title': 'Оставьте заявку',
    
    // Portfolio
    'portfolio.project.beauty.title': 'Beauty Salon Premium',
    'portfolio.project.beauty.category': 'Салон красоты',
    'portfolio.project.beauty.problem': 'Салон терял клиентов из-за отсутствия онлайн-записи',
    'portfolio.project.beauty.solution': 'Создали лендинг с формой записи и интеграцией WhatsApp',
    'portfolio.project.beauty.result': '+150% онлайн-записей за первый месяц',
    'portfolio.project.tech.title': 'TechStore Moldova',
    'portfolio.project.tech.category': 'Электроника',
    'portfolio.project.tech.problem': 'Низкая конверсия продаж онлайн',
    'portfolio.project.tech.solution': 'Разработали интуитивный интернет-магазин с быстрой оплатой',
    'portfolio.project.tech.result': '+200% онлайн-продаж, средний чек вырос на 40%',
    'portfolio.project.law.title': 'Law Firm Pro',
    'portfolio.project.law.category': 'Юридические услуги',
    'portfolio.project.law.problem': 'Устаревший сайт не привлекал новых клиентов',
    'portfolio.project.law.solution': 'Создали современный корпоративный сайт с блогом',
    'portfolio.project.law.result': '+85% входящих заявок, улучшение имиджа компании',
    'portfolio.project.fitness.title': 'Fitness Club Launch',
    'portfolio.project.fitness.category': 'Фитнес-клуб',
    'portfolio.project.fitness.problem': 'Новый клуб нуждался в быстром привлечении членов',
    'portfolio.project.fitness.solution': 'Яркий лендинг с акциями и онлайн-регистрацией',
    'portfolio.project.fitness.result': '300+ новых членов за 2 месяца',
    'portfolio.project.fashion.title': 'Fashion Boutique',
    'portfolio.project.fashion.category': 'Мода',
    'portfolio.project.fashion.problem': 'Бутик хотел выйти в онлайн-продажи',
    'portfolio.project.fashion.solution': 'Элегантный интернет-магазин одежды с примеркой AR',
    'portfolio.project.fashion.result': '€50K+ оборот в первые 3 месяца',
    'portfolio.project.restaurant.title': 'Restaurant Chain',
    'portfolio.project.restaurant.category': 'Ресторанный бизнес',
    'portfolio.project.restaurant.problem': 'Сеть ресторанов нуждалась в единой платформе',
    'portfolio.project.restaurant.solution': 'Многофункциональный сайт с онлайн-заказом и бронированием',
    'portfolio.project.restaurant.result': '+120% онлайн-заказов, экономия на колл-центре',
    'portfolio.project.mded.title': 'Ajutor de Stat MDED',
    'portfolio.project.mded.category': 'Государственный проект',
    'portfolio.project.mded.problem': 'Требовался современный информационный портал о программе государственной поддержки промышленных инвестиций',
    'portfolio.project.mded.solution': 'Многоязычный лендинг на WordPress с ACF, Timber и Twig. Современный дизайн, адаптивная верстка, удобная навигация',
    'portfolio.project.mded.result': 'Профессиональная подача информации о программе, улучшенный UX для граждан и инвесторов',
    
    // Blog
    'blog.categories.all': 'Все статьи',
    'blog.categories.prices': 'Цены',
    'blog.categories.tips': 'Советы',
    'blog.categories.seo': 'SEO',
    'blog.categories.design': 'Дизайн',
    'blog.categories.ecommerce': 'E-commerce',
    'blog.article1.title': 'Сколько стоит создание сайта в Молдове в 2025 году',
    'blog.article1.excerpt': 'Подробный разбор цен на разработку сайтов: от лендингов до интернет-магазинов. Что влияет на стоимость и как не переплатить.',
    'blog.article1.category': 'Цены',
    'blog.article2.title': '10 ошибок при создании сайта для бизнеса',
    'blog.article2.excerpt': 'Типичные ошибки, которые совершают предприниматели при заказе сайта. Как их избежать и сэкономить деньги.',
    'blog.article2.category': 'Советы',
    'blog.article3.title': 'Лендинг или интернет-магазин: что выбрать для старта',
    'blog.article3.excerpt': 'Сравнение типов сайтов для малого бизнеса. Когда нужен лендинг, а когда стоит сразу делать магазин.',
    'blog.article3.category': 'Советы',
    'blog.article4.title': 'SEO-оптимизация сайта: руководство для новичков',
    'blog.article4.excerpt': 'Базовые принципы SEO, которые должен знать каждый владелец сайта. Как подняться в топ Google без больших бюджетов.',
    'blog.article4.category': 'SEO',
    'blog.article5.title': 'Адаптивный дизайн: почему это критично в 2025',
    'blog.article5.excerpt': 'Статистика мобильного трафика в Молдове и почему ваш сайт должен идеально работать на смартфонах.',
    'blog.article5.category': 'Дизайн',
    'blog.article6.title': 'Интеграция платежных систем для интернет-магазина',
    'blog.article6.excerpt': 'Обзор популярных платежных систем в Молдове: комиссии, особенности подключения и безопасность.',
    'blog.article6.category': 'E-commerce',
    'blog.recommended': 'Рекомендуем',
    'blog.newsletter.title': 'Получайте новые статьи',
    'blog.newsletter.subtitle': 'Подпишитесь на рассылку и первыми узнавайте о новых материалах',
    'blog.newsletter.email': 'Ваш email',
    'blog.newsletter.subscribe': 'Подписаться',
    
    // Home
    'home.hero.badge': '🚀 Профессиональная разработка сайтов',
    'home.why.title': 'Почему выбирают',
    'home.why.highlight': 'нас',
    'home.why.subtitle': 'Мы предлагаем полный спектр услуг для создания успешного веб-присутствия вашего бизнеса',
    'home.services.title': 'Наши услуги',
    'home.services.subtitle': 'Выберите подходящее решение для вашего бизнеса',
    'home.services.popular': 'Популярный',
    'home.cta.title': 'Готовы начать',
    'home.cta.highlight': 'свой проект?',
    'home.cta.subtitle': 'Свяжитесь с нами сегодня и получите бесплатную консультацию по вашему проекту',
    
    // NotFound
    'notfound.title': 'Страница не найдена',
    'notfound.subtitle': 'К сожалению, запрашиваемая страница не существует или была перемещена.',
    'notfound.button': 'Вернуться на главную',
    
    // Footer
    'footer.about': 'О компании',
    'footer.about.text': 'Мы создаём современные веб-решения для бизнеса в Молдове',
    'footer.services': 'Услуги',
    'footer.contact': 'Контакты',
    'footer.social': 'Социальные сети',
    'footer.rights': 'Все права защищены',
    
    // Project Detail
    'projectDetail.category': 'Категория',
    'projectDetail.type': 'Тип проекта',
    'projectDetail.client': 'Клиент',
    'projectDetail.date': 'Дата',
    'projectDetail.technologies': 'Технологии',
    
    // Admin Portfolio
    'admin.portfolio.category': 'Категория',
    'admin.portfolio.type': 'Тип проекта',
    'admin.portfolio.typeLabel': 'Тип',
  },
  ro: {
    // Navigation
    'nav.home': 'Acasă',
    'nav.services': 'Servicii',
    'nav.portfolio': 'Portofoliu',
    'nav.blog': 'Blog',
    'nav.contact': 'Contacte',
    
    // Hero
    'hero.title': 'Creăm site-uri care',
    'hero.highlight': 'vând',
    'hero.subtitle': 'Dezvoltare profesională de site-uri în Moldova. Landing pages, magazine online și site-uri corporative la cheie cu garanție de rezultat.',
    'hero.cta': 'Lasă o cerere',
    'hero.consultation': 'Consultație gratuită',
    
    // About
    'about.title': 'Despre noi',
    'about.subtitle': 'WebPoint — o echipă de profesioniști care creează soluții web moderne pentru afacerea ta',
    'about.experience': 'Ani de experiență',
    'about.projects': 'Proiecte',
    'about.clients': 'Clienți mulțumiți',
    
    // Services
    'services.title': 'Serviciile noastre',
    'services.subtitle': 'Alege soluția potrivită pentru afacerea ta',
    'services.landing': 'Landing Page',
    'services.landing.desc': 'Pagină unică de vânzare pentru atragerea clienților și creșterea conversiilor',
    'services.business': 'Site vizită',
    'services.business.desc': 'Site corporativ cu mai multe pagini cu informații complete despre compania ta',
    'services.shop': 'Magazin online',
    'services.shop.desc': 'Magazin online complet funcțional cu catalog, coș și sistem de plată',
    'services.from': 'de la',
    'services.order': 'Comandă',
    'services.time.landing': '7-10 zile',
    'services.time.business': '14-21 zile',
    'services.time.shop': '30-45 zile',
    'services.duration': 'Termen',
    'services.features.landing.design': 'Design modern',
    'services.features.landing.responsive': 'Design responsive',
    'services.features.landing.seo': 'Optimizare SEO',
    'services.features.landing.form': 'Formular de cerere',
    'services.features.business.pages': 'Până la 10 pagini',
    'services.features.business.cms': 'Panou CMS',
    'services.features.business.social': 'Integrare cu rețelele sociale',
    'services.features.business.analytics': 'Analitică',
    'services.features.shop.catalog': 'Catalog de produse',
    'services.features.shop.cart': 'Coș și plată',
    'services.features.shop.account': 'Cont personal',
    'services.features.shop.delivery': 'Integrare livrare',
    'services.features.landing.full.design': 'Design modern unic',
    'services.features.landing.full.responsive': 'Design responsive pentru toate dispozitivele',
    'services.features.landing.full.seo': 'Optimizare SEO și configurare meta tag-uri',
    'services.features.landing.full.form': 'Formular de cerere cu notificări email',
    'services.features.landing.full.analytics': 'Integrare cu Google Analytics',
    'services.features.landing.full.hosting': 'Configurare hosting și domeniu',
    'services.features.landing.full.support': 'Lună de suport tehnic',
    'services.features.landing.full.training': 'Instruire pentru gestionarea conținutului',
    'services.features.business.full.pages': 'Până la 10 pagini informaționale',
    'services.features.business.full.design': 'Design unic adaptat brandului tău',
    'services.features.business.full.cms': 'Panou administrativ (CMS)',
    'services.features.business.full.contact': 'Formular de contact',
    'services.features.business.full.social': 'Integrare cu rețelele sociale',
    'services.features.business.full.blog': 'Blog sau secțiune de știri',
    'services.features.business.full.multilang': 'Multilingvism (RU/RO)',
    'services.features.business.full.maps': 'Integrare Google Maps',
    'services.features.business.full.seo': 'Optimizare SEO pentru toate paginile',
    'services.features.business.full.support': '3 luni de suport tehnic',
    'services.features.shop.full.catalog': 'Catalog de produse cu filtrare',
    'services.features.shop.full.cart': 'Coș și procesare comandă',
    'services.features.shop.full.payment': 'Integrare sisteme de plată',
    'services.features.shop.full.account': 'Cont personal client',
    'services.features.shop.full.admin': 'Panou administrativ',
    'services.features.shop.full.discounts': 'Sistem reduceri și promo-coduri',
    'services.features.shop.full.delivery': 'Integrare servicii de livrare',
    'services.features.shop.full.notifications': 'Notificări email despre comenzi',
    'services.features.shop.full.reviews': 'Recenzii și rating produse',
    'services.features.shop.full.multilang': 'Multilingvism și multi-valută',
    'services.features.shop.full.seo': 'Optimizare SEO produse',
    'services.features.shop.full.support': '6 luni de suport tehnic',
    'services.additional.support.title': 'Suport și dezvoltare',
    'services.additional.support.price': '€50/lună',
    'services.additional.support.content': 'Actualizare conținut',
    'services.additional.support.tech': 'Suport tehnic',
    'services.additional.support.monitoring': 'Monitorizare securitate',
    'services.additional.seo.title': 'Promovare SEO',
    'services.additional.seo.price': '€200/lună',
    'services.additional.seo.analysis': 'Analiză concurenți',
    'services.additional.seo.optimization': 'Optimizare conținut',
    'services.additional.seo.links': 'Lucru cu link-uri',
    'services.additional.ads.title': 'Publicitate contextuală',
    'services.additional.ads.price': '€150/lună',
    'services.additional.ads.google': 'Configurare Google Ads',
    'services.additional.ads.facebook': 'Facebook Ads',
    'services.additional.ads.analytics': 'Analitică și rapoarte',
    'services.additional.more': 'Află mai multe',
    'services.additional.title': 'Servicii suplimentare',
    'services.additional.subtitle': 'Extinde posibilitățile site-ului tău',
    'services.cta.title': 'Nu ai găsit pachetul potrivit?',
    'services.cta.subtitle': 'Vom crea o ofertă personalizată pentru nevoile și bugetul tău',
    'services.cta.button': 'Obține consultație',
    
    // Features
    'features.design': 'Design modern',
    'features.design.desc': 'Design unic adaptat brandului tău',
    'features.responsive': 'Design responsive',
    'features.responsive.desc': 'Afișare corectă pe toate dispozitivele',
    'features.seo': 'Optimizare SEO',
    'features.seo.desc': 'Configurare pentru motoarele de căutare și indexare rapidă',
    'features.support': 'Suport tehnic',
    'features.support.desc': 'Suport și întreținere sub garanție',
    
    // Portfolio
    'portfolio.title': 'Lucrările noastre',
    'portfolio.subtitle': 'Exemple de proiecte realizate cu succes',
    'portfolio.all': 'Toate',
    'portfolio.landing': 'Landing Pages',
    'portfolio.business': 'Site-uri vizită',
    'portfolio.shop': 'Magazine',
    'portfolio.problem': 'Problemă',
    'portfolio.solution': 'Soluție',
    'portfolio.result': 'Rezultat',
    'portfolio.view': 'Vezi proiectul',
    'portfolio.back': 'Înapoi la portofoliu',
    
    // Blog
    'blog.title': 'Blog',
    'blog.subtitle': 'Articole utile despre crearea și promovarea site-urilor',
    'blog.readMore': 'Citește mai mult',
    'blog.readTime': 'min citire',
    'blog.back': 'Înapoi la blog',
    
    // Contact
    'contact.title': 'Contactează-ne',
    'contact.subtitle': 'Pregătit să discutăm proiectul tău? Lasă o cerere și te vom contacta în curând',
    'contact.name': 'Numele tău',
    'contact.email': 'Email',
    'contact.phone': 'Telefon',
    'contact.message': 'Mesaj',
    'contact.projectType': 'Tipul proiectului',
    'contact.send': 'Trimite cererea',
    'contact.sending': 'Se trimite...',
    'contact.success': 'Mulțumim! Te vom contacta în curând.',
    'contact.error': 'A apărut o eroare. Încearcă mai târziu.',
    'contact.phone.label': 'Telefon',
    'contact.email.label': 'Email',
    'contact.address.label': 'Adresă',
    'contact.address.value': 'Chișinău, str. Pușkin 22',
    'contact.quick.title': 'Contact rapid',
    'contact.quick.write': 'Scrie un mesaj',
    'contact.hours.title': 'Program de lucru',
    'contact.hours.weekdays': 'Lun - Vin',
    'contact.hours.weekdays.time': '09:00 - 18:00',
    'contact.hours.saturday': 'Sâmbătă',
    'contact.hours.saturday.time': '10:00 - 15:00',
    'contact.hours.sunday': 'Duminică',
    'contact.hours.sunday.time': 'Zi liberă',
    'contact.faq.title': 'Întrebări frecvente',
    'contact.faq.q1': 'Cât timp durează crearea unui site?',
    'contact.faq.a1': 'Landing page - 7-10 zile, site vizită - 14-21 zile, magazin online - 30-45 zile.',
    'contact.faq.q2': 'Care este forma de plată?',
    'contact.faq.a2': 'Preplată 50% pentru începerea lucrărilor, 50% după predarea proiectului. Posibilă rată.',
    'contact.faq.q3': 'Este inclus suportul tehnic?',
    'contact.faq.a3': 'Da, suport sub garanție de la 1 la 6 luni în funcție de pachet.',
    'contact.faq.q4': 'Pot edita conținutul singur?',
    'contact.faq.a4': 'Da, oferim panou CMS și instruire pentru lucrul cu el.',
    'contact.form.title': 'Lasă o cerere',
    
    // Portfolio
    'portfolio.project.beauty.title': 'Beauty Salon Premium',
    'portfolio.project.beauty.category': 'Salon de frumusețe',
    'portfolio.project.beauty.problem': 'Salonul pierdea clienți din cauza lipsei rezervărilor online',
    'portfolio.project.beauty.solution': 'Am creat un landing page cu formular de rezervare și integrare WhatsApp',
    'portfolio.project.beauty.result': '+150% rezervări online în prima lună',
    'portfolio.project.tech.title': 'TechStore Moldova',
    'portfolio.project.tech.category': 'Electronică',
    'portfolio.project.tech.problem': 'Conversie scăzută a vânzărilor online',
    'portfolio.project.tech.solution': 'Am dezvoltat un magazin online intuitiv cu plată rapidă',
    'portfolio.project.tech.result': '+200% vânzări online, cecul mediu a crescut cu 40%',
    'portfolio.project.law.title': 'Law Firm Pro',
    'portfolio.project.law.category': 'Servicii juridice',
    'portfolio.project.law.problem': 'Site-ul învechit nu atrăgea clienți noi',
    'portfolio.project.law.solution': 'Am creat un site corporativ modern cu blog',
    'portfolio.project.law.result': '+85% cereri primite, îmbunătățirea imaginii companiei',
    'portfolio.project.fitness.title': 'Fitness Club Launch',
    'portfolio.project.fitness.category': 'Club de fitness',
    'portfolio.project.fitness.problem': 'Clubul nou avea nevoie de atragere rapidă a membrilor',
    'portfolio.project.fitness.solution': 'Landing page strălucitor cu promoții și înregistrare online',
    'portfolio.project.fitness.result': '300+ membri noi în 2 luni',
    'portfolio.project.fashion.title': 'Fashion Boutique',
    'portfolio.project.fashion.category': 'Modă',
    'portfolio.project.fashion.problem': 'Boutique-ul dorea să intre în vânzările online',
    'portfolio.project.fashion.solution': 'Magazin online elegant de îmbrăcăminte cu probă AR',
    'portfolio.project.fashion.result': '€50K+ cifră de afaceri în primele 3 luni',
    'portfolio.project.restaurant.title': 'Restaurant Chain',
    'portfolio.project.restaurant.category': 'Business restaurant',
    'portfolio.project.restaurant.problem': 'Lanțul de restaurante avea nevoie de o platformă unificată',
    'portfolio.project.restaurant.solution': 'Site multifuncțional cu comandă online și rezervare',
    'portfolio.project.restaurant.result': '+120% comenzi online, economie la call-center',
    'portfolio.project.mded.title': 'Ajutor de Stat MDED',
    'portfolio.project.mded.category': 'Proiect guvernamental',
    'portfolio.project.mded.problem': 'Era necesar un portal informativ modern despre programul de sprijin de stat pentru investițiile industriale',
    'portfolio.project.mded.solution': 'Landing multilingv pe WordPress cu ACF, Timber și Twig. Design modern, layout adaptiv, navigare intuitivă',
    'portfolio.project.mded.result': 'Prezentare profesională a informațiilor despre program, UX îmbunătățit pentru cetățeni și investitori',
    
    // Blog
    'blog.categories.all': 'Toate articolele',
    'blog.categories.prices': 'Prețuri',
    'blog.categories.tips': 'Sfaturi',
    'blog.categories.seo': 'SEO',
    'blog.categories.design': 'Design',
    'blog.categories.ecommerce': 'E-commerce',
    'blog.article1.title': 'Cât costă crearea unui site în Moldova în 2025',
    'blog.article1.excerpt': 'Analiză detaliată a prețurilor pentru dezvoltarea site-urilor: de la landing pages la magazine online. Ce influențează costul și cum să nu plătești în plus.',
    'blog.article1.category': 'Prețuri',
    'blog.article2.title': '10 greșeli la crearea unui site pentru afacere',
    'blog.article2.excerpt': 'Greșeli tipice pe care le fac antreprenorii la comandarea unui site. Cum să le eviți și să economisești bani.',
    'blog.article2.category': 'Sfaturi',
    'blog.article3.title': 'Landing page sau magazin online: ce să alegi pentru start',
    'blog.article3.excerpt': 'Comparație a tipurilor de site-uri pentru afaceri mici. Când ai nevoie de landing page și când merită să faci imediat magazin.',
    'blog.article3.category': 'Sfaturi',
    'blog.article4.title': 'Optimizare SEO site: ghid pentru începători',
    'blog.article4.excerpt': 'Principii de bază SEO pe care ar trebui să le cunoască fiecare proprietar de site. Cum să urci în top Google fără bugete mari.',
    'blog.article4.category': 'SEO',
    'blog.article5.title': 'Design responsive: de ce este critic în 2025',
    'blog.article5.excerpt': 'Statistici trafic mobil în Moldova și de ce site-ul tău ar trebui să funcționeze perfect pe smartphone-uri.',
    'blog.article5.category': 'Design',
    'blog.article6.title': 'Integrare sisteme de plată pentru magazin online',
    'blog.article6.excerpt': 'Prezentare generală a sistemelor de plată populare în Moldova: comisioane, caracteristici de conectare și securitate.',
    'blog.article6.category': 'E-commerce',
    'blog.recommended': 'Recomandăm',
    'blog.newsletter.title': 'Primește articole noi',
    'blog.newsletter.subtitle': 'Abonează-te la newsletter și află primul despre materialele noi',
    'blog.newsletter.email': 'Email-ul tău',
    'blog.newsletter.subscribe': 'Abonează-te',
    
    // Home
    'home.hero.badge': '🚀 Dezvoltare profesională de site-uri',
    'home.why.title': 'De ce ne aleg',
    'home.why.highlight': 'pe noi',
    'home.why.subtitle': 'Oferim o gamă completă de servicii pentru crearea unei prezențe web de succes pentru afacerea ta',
    'home.services.title': 'Serviciile noastre',
    'home.services.subtitle': 'Alege soluția potrivită pentru afacerea ta',
    'home.services.popular': 'Popular',
    'home.cta.title': 'Gata să începi',
    'home.cta.highlight': 'proiectul tău?',
    'home.cta.subtitle': 'Contactează-ne astăzi și obține o consultație gratuită pentru proiectul tău',
    
    // NotFound
    'notfound.title': 'Pagină negăsită',
    'notfound.subtitle': 'Din păcate, pagina solicitată nu există sau a fost mutată.',
    'notfound.button': 'Înapoi la pagina principală',
    
    // Footer
    'footer.about': 'Despre companie',
    'footer.about.text': 'Creăm soluții web moderne pentru afaceri în Moldova',
    'footer.services': 'Servicii',
    'footer.contact': 'Contacte',
    'footer.social': 'Rețele sociale',
    'footer.rights': 'Toate drepturile rezervate',
    
    // Project Detail
    'projectDetail.category': 'Categorie',
    'projectDetail.type': 'Tipul proiectului',
    'projectDetail.client': 'Client',
    'projectDetail.date': 'Data',
    'projectDetail.technologies': 'Tehnologii',
    
    // Admin Portfolio
    'admin.portfolio.category': 'Categorie',
    'admin.portfolio.type': 'Tipul proiectului',
    'admin.portfolio.typeLabel': 'Tip',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.title': 'We create websites that',
    'hero.highlight': 'sell',
    'hero.subtitle': 'Professional website development in Moldova. Landing pages, online stores and corporate websites turnkey with guaranteed results.',
    'hero.cta': 'Get a quote',
    'hero.consultation': 'Free consultation',
    
    // About
    'about.title': 'About us',
    'about.subtitle': 'WebPoint is a team of professionals creating modern web solutions for your business',
    'about.experience': 'Years of experience',
    'about.projects': 'Projects',
    'about.clients': 'Satisfied clients',
    
    // Services
    'services.title': 'Our services',
    'services.subtitle': 'Choose the right solution for your business',
    'services.landing': 'Landing Page',
    'services.landing.desc': 'Converting single-page website to attract customers and increase conversions',
    'services.business': 'Business Website',
    'services.business.desc': 'Multi-page corporate website with complete information about your company',
    'services.shop': 'Online Store',
    'services.shop.desc': 'Full-featured online store with catalog, shopping cart and payment system',
    'services.from': 'from',
    'services.order': 'Order',
    'services.time.landing': '7-10 days',
    'services.time.business': '14-21 days',
    'services.time.shop': '30-45 days',
    'services.duration': 'Duration',
    'services.features.landing.design': 'Modern design',
    'services.features.landing.responsive': 'Responsive design',
    'services.features.landing.seo': 'SEO optimization',
    'services.features.landing.form': 'Contact form',
    'services.features.business.pages': 'Up to 10 pages',
    'services.features.business.cms': 'CMS admin panel',
    'services.features.business.social': 'Social media integration',
    'services.features.business.analytics': 'Analytics',
    'services.features.shop.catalog': 'Product catalog',
    'services.features.shop.cart': 'Shopping cart & payment',
    'services.features.shop.account': 'Personal account',
    'services.features.shop.delivery': 'Delivery integration',
    'services.features.landing.full.design': 'Unique modern design',
    'services.features.landing.full.responsive': 'Responsive design for all devices',
    'services.features.landing.full.seo': 'SEO optimization and meta tags setup',
    'services.features.landing.full.form': 'Contact form with email notifications',
    'services.features.landing.full.analytics': 'Google Analytics integration',
    'services.features.landing.full.hosting': 'Hosting and domain setup',
    'services.features.landing.full.support': '1 month technical support',
    'services.features.landing.full.training': 'Content management training',
    'services.features.business.full.pages': 'Up to 10 informational pages',
    'services.features.business.full.design': 'Unique design for your brand',
    'services.features.business.full.cms': 'Administrative panel (CMS)',
    'services.features.business.full.contact': 'Contact form',
    'services.features.business.full.social': 'Social media integration',
    'services.features.business.full.blog': 'Blog or news section',
    'services.features.business.full.multilang': 'Multilingual (RU/RO)',
    'services.features.business.full.maps': 'Google Maps integration',
    'services.features.business.full.seo': 'SEO optimization for all pages',
    'services.features.business.full.support': '3 months technical support',
    'services.features.shop.full.catalog': 'Product catalog with filtering',
    'services.features.shop.full.cart': 'Shopping cart and checkout',
    'services.features.shop.full.payment': 'Payment systems integration',
    'services.features.shop.full.account': 'Customer personal account',
    'services.features.shop.full.admin': 'Administrative control panel',
    'services.features.shop.full.discounts': 'Discounts and promo codes system',
    'services.features.shop.full.delivery': 'Delivery services integration',
    'services.features.shop.full.notifications': 'Email notifications for orders',
    'services.features.shop.full.reviews': 'Product reviews and ratings',
    'services.features.shop.full.multilang': 'Multilingual and multi-currency',
    'services.features.shop.full.seo': 'Product SEO optimization',
    'services.features.shop.full.support': '6 months technical support',
    'services.additional.support.title': 'Support and development',
    'services.additional.support.price': '€50/month',
    'services.additional.support.content': 'Content updates',
    'services.additional.support.tech': 'Technical support',
    'services.additional.support.monitoring': 'Security monitoring',
    'services.additional.seo.title': 'SEO promotion',
    'services.additional.seo.price': '€200/month',
    'services.additional.seo.analysis': 'Competitor analysis',
    'services.additional.seo.optimization': 'Content optimization',
    'services.additional.seo.links': 'Link building',
    'services.additional.ads.title': 'Contextual advertising',
    'services.additional.ads.price': '€150/month',
    'services.additional.ads.google': 'Google Ads setup',
    'services.additional.ads.facebook': 'Facebook Ads',
    'services.additional.ads.analytics': 'Analytics and reports',
    'services.additional.more': 'Learn more',
    'services.additional.title': 'Additional services',
    'services.additional.subtitle': 'Expand your website capabilities',
    'services.cta.title': 'Didn\'t find the right package?',
    'services.cta.subtitle': 'We will create a custom offer for your needs and budget',
    'services.cta.button': 'Get consultation',
    
    // Features
    'features.design': 'Modern design',
    'features.design.desc': 'Unique design adapted to your brand',
    'features.responsive': 'Responsive design',
    'features.responsive.desc': 'Correct display on all devices',
    'features.seo': 'SEO optimization',
    'features.seo.desc': 'Setup for search engines and fast indexing',
    'features.support': 'Technical support',
    'features.support.desc': 'Guaranteed support and website maintenance',
    
    // Portfolio
    'portfolio.title': 'Our works',
    'portfolio.subtitle': 'Examples of successfully completed projects',
    'portfolio.all': 'All',
    'portfolio.landing': 'Landing Pages',
    'portfolio.business': 'Business Websites',
    'portfolio.shop': 'Stores',
    'portfolio.problem': 'Problem',
    'portfolio.solution': 'Solution',
    'portfolio.result': 'Result',
    'portfolio.view': 'View project',
    'portfolio.back': 'Back to portfolio',
    
    // Blog
    'blog.title': 'Blog',
    'blog.subtitle': 'Useful articles about website creation and promotion',
    'blog.readMore': 'Read more',
    'blog.readTime': 'min read',
    'blog.back': 'Back to blog',
    
    // Contact
    'contact.title': 'Contact us',
    'contact.subtitle': 'Ready to discuss your project? Leave a request and we will contact you shortly',
    'contact.name': 'Your name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.message': 'Message',
    'contact.projectType': 'Project type',
    'contact.send': 'Send request',
    'contact.sending': 'Sending...',
    'contact.success': 'Thank you! We will contact you shortly.',
    'contact.error': 'An error occurred. Please try again later.',
    'contact.phone.label': 'Phone',
    'contact.email.label': 'Email',
    'contact.address.label': 'Address',
    'contact.address.value': 'Chisinau, Pushkin St. 22',
    'contact.quick.title': 'Quick contact',
    'contact.quick.write': 'Send message',
    'contact.hours.title': 'Working hours',
    'contact.hours.weekdays': 'Mon - Fri',
    'contact.hours.weekdays.time': '09:00 - 18:00',
    'contact.hours.saturday': 'Saturday',
    'contact.hours.saturday.time': '10:00 - 15:00',
    'contact.hours.sunday': 'Sunday',
    'contact.hours.sunday.time': 'Day off',
    'contact.faq.title': 'Frequently asked questions',
    'contact.faq.q1': 'How long does it take to create a website?',
    'contact.faq.a1': 'Landing page - 7-10 days, business website - 14-21 days, online store - 30-45 days.',
    'contact.faq.q2': 'What is the payment method?',
    'contact.faq.a2': '50% prepayment to start work, 50% after project delivery. Installment plan available.',
    'contact.faq.q3': 'Is technical support included?',
    'contact.faq.a3': 'Yes, warranty support from 1 to 6 months depending on the package.',
    'contact.faq.q4': 'Can I edit content myself?',
    'contact.faq.a4': 'Yes, we provide a CMS panel and train you to work with it.',
    'contact.form.title': 'Leave a request',
    
    // Portfolio
    'portfolio.project.beauty.title': 'Beauty Salon Premium',
    'portfolio.project.beauty.category': 'Beauty salon',
    'portfolio.project.beauty.problem': 'Salon was losing clients due to lack of online booking',
    'portfolio.project.beauty.solution': 'Created a landing page with booking form and WhatsApp integration',
    'portfolio.project.beauty.result': '+150% online bookings in the first month',
    'portfolio.project.tech.title': 'TechStore Moldova',
    'portfolio.project.tech.category': 'Electronics',
    'portfolio.project.tech.problem': 'Low online sales conversion',
    'portfolio.project.tech.solution': 'Developed an intuitive online store with fast payment',
    'portfolio.project.tech.result': '+200% online sales, average order value increased by 40%',
    'portfolio.project.law.title': 'Law Firm Pro',
    'portfolio.project.law.category': 'Legal services',
    'portfolio.project.law.problem': 'Outdated website did not attract new clients',
    'portfolio.project.law.solution': 'Created a modern corporate website with blog',
    'portfolio.project.law.result': '+85% incoming requests, improved company image',
    'portfolio.project.fitness.title': 'Fitness Club Launch',
    'portfolio.project.fitness.category': 'Fitness club',
    'portfolio.project.fitness.problem': 'New club needed quick member acquisition',
    'portfolio.project.fitness.solution': 'Bright landing page with promotions and online registration',
    'portfolio.project.fitness.result': '300+ new members in 2 months',
    'portfolio.project.fashion.title': 'Fashion Boutique',
    'portfolio.project.fashion.category': 'Fashion',
    'portfolio.project.fashion.problem': 'Boutique wanted to enter online sales',
    'portfolio.project.fashion.solution': 'Elegant online clothing store with AR try-on',
    'portfolio.project.fashion.result': '€50K+ turnover in the first 3 months',
    'portfolio.project.restaurant.title': 'Restaurant Chain',
    'portfolio.project.restaurant.category': 'Restaurant business',
    'portfolio.project.restaurant.problem': 'Restaurant chain needed a unified platform',
    'portfolio.project.restaurant.solution': 'Multifunctional website with online ordering and booking',
    'portfolio.project.restaurant.result': '+120% online orders, savings on call center',
    'portfolio.project.mded.title': 'State Aid MDED',
    'portfolio.project.mded.category': 'Government project',
    'portfolio.project.mded.problem': 'A modern information portal was needed about the state support program for industrial investments',
    'portfolio.project.mded.solution': 'Multilingual landing page on WordPress with ACF, Timber and Twig. Modern design, responsive layout, intuitive navigation',
    'portfolio.project.mded.result': 'Professional presentation of program information, improved UX for citizens and investors',
    
    // Blog
    'blog.categories.all': 'All articles',
    'blog.categories.prices': 'Prices',
    'blog.categories.tips': 'Tips',
    'blog.categories.seo': 'SEO',
    'blog.categories.design': 'Design',
    'blog.categories.ecommerce': 'E-commerce',
    'blog.article1.title': 'How much does website creation cost in Moldova in 2025',
    'blog.article1.excerpt': 'Detailed breakdown of website development prices: from landing pages to online stores. What affects the cost and how not to overpay.',
    'blog.article1.category': 'Prices',
    'blog.article2.title': '10 mistakes when creating a website for business',
    'blog.article2.excerpt': 'Typical mistakes entrepreneurs make when ordering a website. How to avoid them and save money.',
    'blog.article2.category': 'Tips',
    'blog.article3.title': 'Landing page or online store: what to choose for startup',
    'blog.article3.excerpt': 'Comparison of website types for small businesses. When you need a landing page and when it\'s worth making a store right away.',
    'blog.article3.category': 'Tips',
    'blog.article4.title': 'Website SEO optimization: guide for beginners',
    'blog.article4.excerpt': 'Basic SEO principles every website owner should know. How to get to the top of Google without big budgets.',
    'blog.article4.category': 'SEO',
    'blog.article5.title': 'Responsive design: why it\'s critical in 2025',
    'blog.article5.excerpt': 'Mobile traffic statistics in Moldova and why your website should work perfectly on smartphones.',
    'blog.article5.category': 'Design',
    'blog.article6.title': 'Payment systems integration for online store',
    'blog.article6.excerpt': 'Overview of popular payment systems in Moldova: fees, connection features and security.',
    'blog.article6.category': 'E-commerce',
    'blog.recommended': 'Recommended',
    'blog.newsletter.title': 'Get new articles',
    'blog.newsletter.subtitle': 'Subscribe to newsletter and be the first to know about new materials',
    'blog.newsletter.email': 'Your email',
    'blog.newsletter.subscribe': 'Subscribe',
    
    // Home
    'home.hero.badge': '🚀 Professional website development',
    'home.why.title': 'Why choose',
    'home.why.highlight': 'us',
    'home.why.subtitle': 'We offer a full range of services to create a successful web presence for your business',
    'home.services.title': 'Our services',
    'home.services.subtitle': 'Choose the right solution for your business',
    'home.services.popular': 'Popular',
    'home.cta.title': 'Ready to start',
    'home.cta.highlight': 'your project?',
    'home.cta.subtitle': 'Contact us today and get a free consultation for your project',
    
    // NotFound
    'notfound.title': 'Page not found',
    'notfound.subtitle': 'Unfortunately, the requested page does not exist or has been moved.',
    'notfound.button': 'Back to home',
    
    // Footer
    'footer.about': 'About company',
    'footer.about.text': 'We create modern web solutions for businesses in Moldova',
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.social': 'Social networks',
    'footer.rights': 'All rights reserved',
    
    // Project Detail
    'projectDetail.category': 'Category',
    'projectDetail.type': 'Project Type',
    'projectDetail.client': 'Client',
    'projectDetail.date': 'Date',
    'projectDetail.technologies': 'Technologies',
    
    // Admin Portfolio
    'admin.portfolio.category': 'Category',
    'admin.portfolio.type': 'Project Type',
    'admin.portfolio.typeLabel': 'Type',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'webpoint-language';

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  // Загружаем язык из localStorage при инициализации
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY) as Language;
      if (savedLanguage && (savedLanguage === 'ru' || savedLanguage === 'ro' || savedLanguage === 'en')) {
        return savedLanguage;
      }
    }
    return 'ru';
  });

  // Сохраняем язык в localStorage при изменении
  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    }
  }, [language]);

  // Обертка для setLanguage, чтобы сохранять в localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const langTranslations = translations[language];
    return (langTranslations[key as keyof typeof langTranslations] as string) || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
