import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ru' | 'ro' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.services': 'Услуги',
    'nav.portfolio': 'Портфолио',
    'nav.blog': 'Блог',
    'nav.contact': 'Контакты',
    'home.services.web.title': 'Веб-решения',
    'home.services.web.desc': 'Создаем современные сайты и масштабируемые платформы любой сложности.',
    'home.services.tg.title': 'Telegram системы',
    'home.services.tg.desc': 'Разрабатываем экосистемы внутри мессенджера: от ботов до Mini Apps.',
    'home.services.auto.title': 'AI & Автоматизация',
    'home.services.auto.desc': 'Внедряем ИИ и автоматизируем рутину, освобождая время для роста бизнеса.',
    'home.services.mobile.title': 'Mobile разработка',
    'home.services.mobile.desc': 'Создаем быстрые и интуитивные приложения для iOS и Android.',

    // Hero
    'hero.title': 'Разработка высокотехнологичных',
    'hero.highlight': 'ИТ-решений',
    'hero.subtitle': 'Создаем эффективные цифровые продукты для бизнеса: от корпоративных сайтов до мобильных приложений, Telegram-экосистем и автоматизации с ИИ.',
    'hero.cta': 'Оставить заявку',
    'hero.consultation': 'Бесплатная консультация',

    // About
    'about.title': 'О нас',
    'about.subtitle': 'WebPoint — это команда профессионалов, которая создаёт современные веб-решения для вашего бизнеса',
    'about.experience': 'Лет опыта',
    'about.projects': 'Проектов',
    'about.clients': 'Довольных клиентов',

    // Services
    'services.title': 'Наши услуги',
    'services.subtitle': 'Выберите подходящее решение для вашего бизнеса',
    'services.landing': 'Лендинг',
    'services.landing.desc': 'Продающая одностраничная страница для привлечения клиентов и увеличения конверсии',
    'services.business': 'Сайт-визитка',
    'services.business.desc': 'Многостраничный корпоративный сайт с полной информацией о вашей компании',
    'services.shop': 'Интернет-магазин',
    'services.shop.desc': 'Полнофункциональный онлайн-магазин с каталогом, корзиной и системой оплаты',
    'services.from': 'от',
    'services.order': 'Заказать',
    'services.time.landing': '7-10 дней',
    'services.time.business': '14-21 день',
    'services.time.shop': '30-45 дней',
    'services.duration': 'Срок',
    'services.popular.badge': 'Популярный выбор',
    'services.features.landing.design': 'Современный дизайн',
    'services.features.landing.responsive': 'Адаптивная верстка',
    'services.features.landing.seo': 'SEO-оптимизация',
    'services.features.landing.form': 'Форма заявки',
    'services.features.business.pages': 'До 10 страниц',
    'services.features.business.cms': 'CMS админ-панель',
    'services.features.business.social': 'Интеграция с соцсетями',
    'services.features.business.analytics': 'Аналитика',
    'services.features.shop.catalog': 'Каталог товаров',
    'services.features.shop.cart': 'Корзина и оплата',
    'services.features.shop.account': 'Личный кабинет',
    'services.features.shop.delivery': 'Интеграция доставки',
    'services.features.landing.full.design': 'Уникальный современный дизайн',
    'services.features.landing.full.responsive': 'Адаптивная верстка для всех устройств',
    'services.features.landing.full.seo': 'SEO-оптимизация и настройка метатегов',
    'services.features.landing.full.form': 'Форма заявки с email-уведомлениями',
    'services.features.landing.full.analytics': 'Интеграция с Google Analytics',
    'services.features.landing.full.hosting': 'Настройка хостинга и домена',
    'services.features.landing.full.support': 'Месяц технической поддержки',
    'services.features.landing.full.training': 'Обучение по управлению контентом',
    'services.features.business.full.pages': 'До 10 информационных страниц',
    'services.features.business.full.design': 'Уникальный дизайн под ваш бренд',
    'services.features.business.full.cms': 'Административная панель (CMS)',
    'services.features.business.full.contact': 'Форма обратной связи',
    'services.features.business.full.social': 'Интеграция с социальными сетями',
    'services.features.business.full.blog': 'Блог или новостной раздел',
    'services.features.business.full.multilang': 'Мультиязычность (RU/RO)',
    'services.features.business.full.maps': 'Google Maps интеграция',
    'services.features.business.full.seo': 'SEO-оптимизация всех страниц',
    'services.features.business.full.support': '3 месяца технической поддержки',
    'services.features.shop.full.catalog': 'Каталог товаров с фильтрацией',
    'services.features.shop.full.cart': 'Корзина и оформление заказа',
    'services.features.shop.full.payment': 'Интеграция платежных систем',
    'services.features.shop.full.account': 'Личный кабинет клиента',
    'services.features.shop.full.admin': 'Административная панель управления',
    'services.features.shop.full.discounts': 'Система скидок и промокодов',
    'services.features.shop.full.delivery': 'Интеграция служб доставки',
    'services.features.shop.full.notifications': 'Email-уведомления о заказах',
    'services.features.shop.full.reviews': 'Отзывы и рейтинг товаров',
    'services.features.shop.full.multilang': 'Мультиязычность и мультивалютность',
    'services.features.shop.full.seo': 'SEO-оптимизация товаров',
    'services.features.shop.full.support': '6 месяцев технической поддержки',
    'services.additional.support.title': 'Поддержка и развитие',
    'services.additional.support.desc': 'Комплексное сопровождение и развитие вашего сайта. Обеспечиваем регулярное обновление контента, техническую поддержку и мониторинг безопасности.',
    'services.additional.support.price': '€50/мес',
    'services.additional.support.content': 'Обновление контента',
    'services.additional.support.tech': 'Техническая поддержка',
    'services.additional.support.monitoring': 'Мониторинг безопасности',
    'services.additional.seo.title': 'SEO-продвижение',
    'services.additional.seo.desc': 'Профессиональное SEO-продвижение вашего сайта в поисковых системах. Проводим анализ конкурентов, оптимизируем контент и настраиваем ссылочную структуру для повышения позиций.',
    'services.additional.seo.price': '€200/мес',
    'services.additional.seo.analysis': 'Анализ конкурентов',
    'services.additional.seo.optimization': 'Оптимизация контента',
    'services.additional.seo.links': 'Работа со ссылками',
    'services.additional.ads.title': 'Контекстная реклама',
    'services.additional.ads.desc': 'Настройка и ведение контекстной рекламы для привлечения целевой аудитории. Работаем с Google Ads и Facebook Ads, предоставляем детальную аналитику и отчеты.',
    'services.additional.ads.price': '€150/мес',
    'services.additional.ads.google': 'Настройка Google Ads',
    'services.additional.ads.facebook': 'Facebook Ads',
    'services.additional.ads.analytics': 'Аналитика и отчеты',
    'services.additional.more': 'Узнать подробнее',
    'services.additional.title': 'Дополнительные услуги',
    'services.additional.subtitle': 'Расширьте возможности вашего сайта',
    'services.category.websites': 'Веб-сайты',
    'services.category.telegram': 'Telegram боты',
    'services.category.automation': 'Автоматизация',
    'services.category.mobile': 'Мобильные приложения',

    // Mobile Packages RU
    'services.mobile.mvp': 'Быстрый старт (MVP)',
    'services.mobile.mvp.desc': 'Быстрая проверка гипотез. Создаем функциональное приложение, которое работает на Android, iOS и в Web одновременно.',
    'services.mobile.business': 'Бизнес-приложение',
    'services.mobile.business.desc': 'Мощный инструмент для вашего бренда. Полноценный запуск в App Store и Google Play с Push-уведомлениями.',
    'services.mobile.shop': 'Мобильный магазин',
    'services.mobile.shop.desc': 'Ваш магазин в кармане клиента. Максимальное удобство покупки с интеграцией Apple Pay и Google Pay.',

    'services.time.mobile.mvp': '14-21 день',
    'services.time.mobile.business': '30-45 дней',
    'services.time.mobile.shop': '45-60 дней',

    'services.features.mobile.mvp.hybrid': 'Android + iOS + Web',
    'services.features.mobile.mvp.auth': 'Авторизация и профиль',
    'services.features.mobile.mvp.adaptive': 'Адаптивный UI/UX дизайн',
    'services.features.mobile.mvp.social': 'Регистрация через соцсети',
    'services.features.mobile.mvp.analytics': 'Базовая аналитика (Firebase)',
    'services.features.mobile.business.stores': 'Публикация в App Store / Google Play',
    'services.features.mobile.business.push': 'Push-уведомления',
    'services.features.mobile.business.native': 'Доступ к функциям смартфона',
    'services.features.mobile.business.offline': 'Оффлайн хранилище данных',
    'services.features.mobile.business.geo': 'Геолокация и карты',
    'services.features.mobile.shop.pay': 'Apple Pay / Google Pay',
    'services.features.mobile.shop.ota': 'Мгновенные обновления (OTA)',
    'services.features.mobile.shop.offline': 'Работа в оффлайн режиме',
    'services.features.mobile.shop.search': 'Умный поиск и фильтры',
    'services.features.mobile.shop.history': 'История заказов и статусы',

    // Telegram Packages RU
    'services.tg.basic': 'Бот-визитка',
    'services.tg.basic.desc': 'Идеально для презентации услуг, записи клиентов и ответов на частые вопросы в мессенджере.',
    'services.tg.shop': 'Магазин в Telegram',
    'services.tg.shop.desc': 'Полноценные продажи внутри Telegram. Каталог, корзина и прием платежей без перехода на сайт.',
    'services.tg.complex': 'Сложные системы',
    'services.tg.complex.desc': 'Индивидуальные решения: интеграция с API, автоматизация администрирования каналов и чатов.',

    'services.time.tg.basic': '3-5 дней',
    'services.time.tg.shop': '7-14 дней',
    'services.time.tg.complex': 'от 10 дней',

    'services.features.tg.basic.menu': 'Интерактивное меню',
    'services.features.tg.basic.faq': 'Ответы на вопросы (FAQ)',
    'services.features.tg.basic.form': 'Форма сбора заявок',
    'services.features.tg.basic.admin': 'Мини-админ панель',
    'services.features.tg.basic.broadcast': 'Массовые рассылки',
    'services.features.tg.basic.stats': 'Статистика пользователей',
    'services.features.tg.shop.catalog': 'Каталог товаров',
    'services.features.tg.shop.cart': 'Корзина и оформление',
    'services.features.tg.shop.payments': 'Прием платежей',
    'services.features.tg.shop.notification': 'Уведомления о заказах',
    'services.features.tg.shop.ref': 'Реферальная система (MGM)',
    'services.features.tg.shop.sheets': 'Интеграция с Google Таблицами',
    'services.features.tg.complex.api': 'Интеграция с внешним API',
    'services.features.tg.complex.db': 'База данных пользователей',
    'services.features.tg.complex.custom': 'Индивидуальная логика',
    'services.features.tg.complex.ai': 'Интеграция с ИИ (ChatGPT)',
    'services.features.tg.complex.subs': 'Система платных подписок',

    // Automation Packages RU
    'services.auto.parsing': 'Парсинг данных',
    'services.auto.parsing.desc': 'Автоматический сбор информации с любых сайтов и маркетплейсов в удобном формате (Excel/JSON).',
    'services.auto.scripts': 'Кастомные скрипты',
    'services.auto.scripts.desc': 'Разработка скриптов для автоматизации рутинных задач, обработки файлов и системного администрирования.',
    'services.auto.complex': 'Умная платформа',
    'services.auto.complex.desc': 'Веб-платформа с глубокой интеграцией инструментов автоматизации, парсинга данных и ИИ.',

    'services.time.auto.parsing': '3-5 дней',
    'services.time.auto.scripts': 'от 3 дней',
    'services.time.auto.complex': 'от 14 дней',

    'services.features.auto.parsing.sites': 'Сбор с любых сайтов',
    'services.features.auto.parsing.format': 'Удобный формат выгрузки',
    'services.features.auto.parsing.schedule': 'Запуск по расписанию',
    'services.features.auto.parsing.stealth': 'Защита от блокировок (Proxy)',
    'services.features.auto.scripts.routine': 'Автоматизация рутины',
    'services.features.auto.scripts.clean': 'Чистый и понятный код',
    'services.features.auto.scripts.support': 'Сопровождение и поддержка',
    'services.features.auto.scripts.secure': 'Защищенное шифрование данных',
    'services.features.auto.scripts.docs': 'Инструкции и документация',
    'services.features.auto.complex.web': 'Веб-интерфейс управления',
    'services.features.auto.complex.parsing': 'Встроенный парсинг данных',
    'services.features.auto.complex.scripts': 'Автоматизация бизнес-процессов',
    'services.features.auto.complex.ai': 'Интеграция с AI (GPT-4/Claude)',
    'services.features.auto.complex.notif': 'Система уведомлений',

    'services.cta.title': 'Не нашли подходящий пакет?',
    'services.cta.subtitle': 'Мы создадим индивидуальное предложение под ваши задачи и бюджет',
    'services.cta.button': 'Получить консультацию',

    // Features
    'features.tech': 'Технологический стек',
    'features.tech.desc': 'Используем передовые инструменты: React, Next.js, Python и нейросети.',
    'features.business': 'Бизнес-результат',
    'features.business.desc': 'Фокусируемся на целях вашего бизнеса и возврате инвестиций (ROI).',
    'features.ai': 'AI Инновации',
    'features.ai.desc': 'Внедряем искусственный интеллект для автоматизации рутинных процессов.',
    'features.support': 'Партнерство 24/7',
    'features.support.desc': 'Сопровождаем ваш проект на всех этапах: от идеи до масштабирования.',

    // Portfolio
    'portfolio.title': 'Наши работы',
    'portfolio.subtitle': 'Примеры успешно реализованных проектов',
    'portfolio.all': 'Все',
    'portfolio.landing': 'Лендинги',
    'portfolio.business': 'Сайты-визитки',
    'portfolio.shop': 'Магазины',
    'portfolio.problem': 'Проблема',
    'portfolio.solution': 'Решение',
    'portfolio.result': 'Результат',
    'portfolio.view': 'Посмотреть проект',
    'portfolio.back': 'Вернуться к портфолио',

    // Blog
    'blog.title': 'Блог',
    'blog.subtitle': 'Полезные статьи о создании и продвижении сайтов',
    'blog.readMore': 'Читать далее',
    'blog.readTime': 'мин чтения',
    'blog.back': 'Вернуться к блогу',

    // Contact
    'contact.title': 'Свяжитесь с нами',
    'contact.subtitle': 'Готовы обсудить ваш проект? Оставьте заявку, и мы свяжемся с вами в ближайшее время',
    'contact.name': 'Ваше имя',
    'contact.email': 'Email',
    'contact.phone': 'Телефон',
    'contact.message': 'Сообщение',
    'contact.projectType': 'Тип проекта',
    'contact.send': 'Отправить заявку',
    'contact.sending': 'Отправка...',
    'contact.success': 'Спасибо! Мы свяжемся с вами в ближайшее время.',
    'contact.error': 'Произошла ошибка. Попробуйте позже.',
    'contact.phone.label': 'Телефон',
    'contact.email.label': 'Email',
    'contact.address.label': 'Адрес',
    'contact.address.value': 'Кишинёв, ул. Пушкина 22',
    'contact.quick.title': 'Быстрая связь',
    'contact.quick.write': 'Написать сообщение',
    'contact.hours.title': 'Время работы',
    'contact.hours.weekdays': 'Пн - Пт',
    'contact.hours.weekdays.time': '09:00 - 18:00',
    'contact.hours.saturday': 'Суббота',
    'contact.hours.saturday.time': '10:00 - 15:00',
    'contact.hours.sunday': 'Воскресенье',
    'contact.hours.sunday.time': 'Выходной',
    'contact.faq.title': 'Часто задаваемые вопросы',
    'contact.faq.q1': 'Как долго создаётся сайт?',
    'contact.faq.a1': 'Лендинг - 7-10 дней, сайт-визитка - 14-21 день, интернет-магазин - 30-45 дней.',
    'contact.faq.q2': 'Какая форма оплаты?',
    'contact.faq.a2': 'Предоплата 50% для начала работ, 50% после сдачи проекта. Возможна рассрочка.',
    'contact.faq.q3': 'Включена ли техподдержка?',
    'contact.faq.a3': 'Да, гарантийная поддержка от 1 до 6 месяцев в зависимости от пакета.',
    'contact.faq.q4': 'Можно ли самому редактировать контент?',
    'contact.faq.a4': 'Да, мы предоставляем CMS-панель и обучаем работе с ней.',
    'contact.form.title': 'Оставьте заявку',

    // Portfolio
    'portfolio.project.beauty.title': 'Beauty Salon Premium',
    'portfolio.project.beauty.category': 'Салон красоты',
    'portfolio.project.beauty.problem': 'Салон терял клиентов из-за отсутствия онлайн-записи',
    'portfolio.project.beauty.solution': 'Создали лендинг с формой записи и интеграцией WhatsApp',
    'portfolio.project.beauty.result': '+150% онлайн-записей за первый месяц',
    'portfolio.project.tech.title': 'TechStore Moldova',
    'portfolio.project.tech.category': 'Электроника',
    'portfolio.project.tech.problem': 'Низкая конверсия продаж онлайн',
    'portfolio.project.tech.solution': 'Разработали интуитивный интернет-магазин с быстрой оплатой',
    'portfolio.project.tech.result': '+200% онлайн-продаж, средний чек вырос на 40%',
    'portfolio.project.law.title': 'Law Firm Pro',
    'portfolio.project.law.category': 'Юридические услуги',
    'portfolio.project.law.problem': 'Устаревший сайт не привлекал новых клиентов',
    'portfolio.project.law.solution': 'Создали современный корпоративный сайт с блогом',
    'portfolio.project.law.result': '+85% входящих заявок, улучшение имиджа компании',
    'portfolio.project.fitness.title': 'Fitness Club Launch',
    'portfolio.project.fitness.category': 'Фитнес-клуб',
    'portfolio.project.fitness.problem': 'Новый клуб нуждался в быстром привлечении членов',
    'portfolio.project.fitness.solution': 'Яркий лендинг с акциями и онлайн-регистрацией',
    'portfolio.project.fitness.result': '300+ новых членов за 2 месяца',
    'portfolio.project.fashion.title': 'Fashion Boutique',
    'portfolio.project.fashion.category': 'Мода',
    'portfolio.project.fashion.problem': 'Бутик хотел выйти в онлайн-продажи',
    'portfolio.project.fashion.solution': 'Элегантный интернет-магазин одежды с примеркой AR',
    'portfolio.project.fashion.result': '€50K+ оборот в первые 3 месяца',
    'portfolio.project.restaurant.title': 'Restaurant Chain',
    'portfolio.project.restaurant.category': 'Ресторанный бизнес',
    'portfolio.project.restaurant.problem': 'Сеть ресторанов нуждалась в единой платформе',
    'portfolio.project.restaurant.solution': 'Многофункциональный сайт с онлайн-заказом и бронированием',
    'portfolio.project.restaurant.result': '+120% онлайн-заказов, экономия на колл-центре',
    'portfolio.project.mded.title': 'Ajutor de Stat MDED',
    'portfolio.project.mded.category': 'Государственный проект',
    'portfolio.project.mded.problem': 'Требовался современный информационный портал о программе государственной поддержки промышленных инвестиций',
    'portfolio.project.mded.solution': 'Многоязычный лендинг на WordPress с ACF, Timber и Twig. Современный дизайн, адаптивная верстка, удобная навигация',
    'portfolio.project.mded.result': 'Профессиональная подача информации о программе, улучшенный UX для граждан и инвесторов',

    // Blog
    'blog.categories.all': 'Все статьи',
    'blog.categories.prices': 'Цены',
    'blog.categories.tips': 'Советы',
    'blog.categories.seo': 'SEO',
    'blog.categories.design': 'Дизайн',
    'blog.categories.ecommerce': 'E-commerce',
    'blog.article1.title': 'Сколько стоит создание сайта в Молдове в 2025 году',
    'blog.article1.excerpt': 'Подробный разбор цен на разработку сайтов: от лендингов до интернет-магазинов. Что влияет на стоимость и как не переплатить.',
    'blog.article1.category': 'Цены',
    'blog.article2.title': '10 ошибок при создании сайта для бизнеса',
    'blog.article2.excerpt': 'Типичные ошибки, которые совершают предприниматели при заказе сайта. Как их избежать и сэкономить деньги.',
    'blog.article2.category': 'Советы',
    'blog.article3.title': 'Лендинг или интернет-магазин: что выбрать для старта',
    'blog.article3.excerpt': 'Сравнение типов сайтов для малого бизнеса. Когда нужен лендинг, а когда стоит сразу делать магазин.',
    'blog.article3.category': 'Советы',
    'blog.article4.title': 'SEO-оптимизация сайта: руководство для новичков',
    'blog.article4.excerpt': 'Базовые принципы SEO, которые должен знать каждый владелец сайта. Как подняться в топ Google без больших бюджетов.',
    'blog.article4.category': 'SEO',
    'blog.article5.title': 'Адаптивный дизайн: почему это критично в 2025',
    'blog.article5.excerpt': 'Статистика мобильного трафика в Молдове и почему ваш сайт должен идеально работать на смартфонах.',
    'blog.article5.category': 'Дизайн',
    'blog.article6.title': 'Интеграция платежных систем для интернет-магазина',
    'blog.article6.excerpt': 'Обзор популярных платежных систем в Молдове: комиссии, особенности подключения и безопасность.',
    'blog.article6.category': 'E-commerce',
    'blog.recommended': 'Рекомендуем',
    'blog.newsletter.title': 'Получайте новые статьи',
    'blog.newsletter.title.prefix': 'Получайте ',
    'blog.newsletter.title.highlight': 'новые статьи',
    'blog.newsletter.subtitle': 'Подпишитесь на рассылку и первыми узнавайте о новых материалах',
    'blog.newsletter.email': 'Ваш email',
    'blog.newsletter.subscribe': 'Подписаться',
    'blog.newsletter.success': 'Спасибо за подписку! Мы свяжемся с вами, когда выйдет новая статья.',
    'blog.newsletter.error': 'Произошла ошибка. Попробуйте позже.',
    'blog.newsletter.exists': 'Вы уже подписаны!',
    'blog.newsletter.sending': 'Отправка...',

    // Home
    'home.hero.badge': '�️ Высокотехнологичные ИТ-решения для бизнеса',
    'home.why.title': 'Почему выбирают',
    'home.why.highlight': 'WebPoint',
    'home.why.subtitle': 'Мы внедряем передовые технологии и автоматизацию, чтобы ваш бизнес рос быстрее и работал эффективнее.',
    'home.stats.title_suffix': 'в цифрах',
    'home.stats.subtitle': 'Реальные показатели нашего опыта и доверия клиентов',
    'home.services.title': 'Наши услуги',
    'home.services.subtitle': 'Выберите подходящее решение для вашего бизнеса',
    'home.services.popular': 'Популярный',
    'home.cta.title': 'Готовы начать',
    'home.cta.highlight': 'свой проект?',
    'home.cta.subtitle': 'Свяжитесь с нами сегодня и получите бесплатную консультацию по вашему проекту',

    // NotFound
    'notfound.title': 'Страница не найдена',
    'notfound.subtitle': 'К сожалению, запрашиваемая страница не существует или была перемещена.',
    'notfound.button': 'Вернуться на главную',

    // Footer
    'footer.about': 'О компании',
    'footer.about.text': 'Мы создаем высокотехнологичные ИТ-решения и цифровые системы для бизнеса по всему миру',
    'footer.services': 'Услуги',
    'footer.contact': 'Контакты',
    'footer.social': 'Социальные сети',
    'footer.rights': 'Все права защищены',

    // Project Detail
    'projectDetail.category': 'Категория',
    'projectDetail.type': 'Тип проекта',
    'projectDetail.client': 'Клиент',
    'projectDetail.date': 'Дата',
    'projectDetail.technologies': 'Технологии',

    // Admin Portfolio
    'admin.portfolio.category': 'Категория',
    'admin.portfolio.type': 'Тип проекта',
    'admin.portfolio.typeLabel': 'Тип',
  },
  ro: {
    // Navigation
    'nav.home': 'Acasă',
    'nav.services': 'Servicii',
    'nav.portfolio': 'Portofoliu',
    'nav.blog': 'Blog',
    'nav.contact': 'Contacte',
    'home.services.web.title': 'Soluții Web',
    'home.services.web.desc': 'Creăm site-uri moderne și platforme scalabile de orice complexitate.',
    'home.services.tg.title': 'Sisteme Telegram',
    'home.services.tg.desc': 'Dezvoltăm ecosisteme în mesager: de la botași la Mini Apps.',
    'home.services.auto.title': 'AI & Automatizare',
    'home.services.auto.desc': 'Implementăm AI și automatizăm rutina, eliberând timp pentru creștere.',
    'home.services.mobile.title': 'Dezvoltare Mobile',
    'home.services.mobile.desc': 'Creăm aplicații rapide și intuitive pentru iOS și Android.',

    // Hero
    'hero.title': 'Dezvoltarea soluțiilor IT',
    'hero.highlight': 'de înaltă tehnologie',
    'hero.subtitle': 'Creăm produse digitale eficiente pentru afaceri: de la site-uri corporative la aplicații mobile, ecosisteme Telegram și automatizare cu AI.',
    'hero.cta': 'Lasă o cerere',
    'hero.consultation': 'Consultație gratuită',

    // About
    'about.title': 'Despre noi',
    'about.subtitle': 'WebPoint — o echipă de profesioniști care creează soluții web moderne pentru afacerea ta',
    'about.experience': 'Ani de experiență',
    'about.projects': 'Proiecte',
    'about.clients': 'Clienți mulțumiți',

    // Services
    'services.title': 'Serviciile noastre',
    'services.subtitle': 'Alege soluția potrivită pentru afacerea ta',
    'services.landing': 'Landing Page',
    'services.landing.desc': 'Pagină unică de vânzare pentru atragerea clienților și creșterea conversiilor',
    'services.business': 'Site vizită',
    'services.business.desc': 'Site corporativ cu mai multe pagini cu informații complete despre compania ta',
    'services.shop': 'Magazin online',
    'services.shop.desc': 'Magazin online complet funcțional cu catalog, coș și sistem de plată',
    'services.from': 'de la',
    'services.order': 'Comandă',
    'services.time.landing': '7-10 zile',
    'services.time.business': '14-21 zile',
    'services.time.shop': '30-45 zile',
    'services.duration': 'Termen',
    'services.popular.badge': 'Alegere populară',
    'services.features.landing.design': 'Design modern',
    'services.features.landing.responsive': 'Design responsive',
    'services.features.landing.seo': 'Optimizare SEO',
    'services.features.landing.form': 'Formular de cerere',
    'services.features.business.pages': 'Până la 10 pagini',
    'services.features.business.cms': 'Panou CMS',
    'services.features.business.social': 'Integrare cu rețelele sociale',
    'services.features.business.analytics': 'Analitică',
    'services.features.shop.catalog': 'Catalog de produse',
    'services.features.shop.cart': 'Coș și plată',
    'services.features.shop.account': 'Cont personal',
    'services.features.shop.delivery': 'Integrare livrare',
    'services.features.landing.full.design': 'Design modern unic',
    'services.features.landing.full.responsive': 'Design responsive pentru toate dispozitivele',
    'services.features.landing.full.seo': 'Optimizare SEO și configurare meta tag-uri',
    'services.features.landing.full.form': 'Formular de cerere cu notificări email',
    'services.features.landing.full.analytics': 'Integrare cu Google Analytics',
    'services.features.landing.full.hosting': 'Configurare hosting și domeniu',
    'services.features.landing.full.support': 'Lună de suport tehnic',
    'services.features.landing.full.training': 'Instruire pentru gestionarea conținutului',
    'services.features.business.full.pages': 'Până la 10 pagini informaționale',
    'services.features.business.full.design': 'Design unic adaptat brandului tău',
    'services.features.business.full.cms': 'Panou administrativ (CMS)',
    'services.features.business.full.contact': 'Formular de contact',
    'services.features.business.full.social': 'Integrare cu rețelele sociale',
    'services.features.business.full.blog': 'Blog sau secțiune de știri',
    'services.features.business.full.multilang': 'Multilingvism (RU/RO)',
    'services.features.business.full.maps': 'Integrare Google Maps',
    'services.features.business.full.seo': 'Optimizare SEO pentru toate paginile',
    'services.features.business.full.support': '3 luni de suport tehnic',
    'services.features.shop.full.catalog': 'Catalog de produse cu filtrare',
    'services.features.shop.full.cart': 'Coș și procesare comandă',
    'services.features.shop.full.payment': 'Integrare sisteme de plată',
    'services.features.shop.full.account': 'Cont personal client',
    'services.features.shop.full.admin': 'Panou administrativ',
    'services.features.shop.full.discounts': 'Sistem reduceri și promo-coduri',
    'services.features.shop.full.delivery': 'Integrare servicii de livrare',
    'services.features.shop.full.notifications': 'Notificări email despre comenzi',
    'services.features.shop.full.reviews': 'Recenzii și rating produse',
    'services.features.shop.full.multilang': 'Multilingvism și multi-valută',
    'services.features.shop.full.seo': 'Optimizare SEO produse',
    'services.features.shop.full.support': '6 luni de suport tehnic',
    'services.additional.support.title': 'Suport și dezvoltare',
    'services.additional.support.desc': 'Îngrijire și dezvoltare completă a site-ului dvs. Oferim actualizări regulate de conținut, suport tehnic și monitorizare a securității.',
    'services.additional.support.price': '€50/lună',
    'services.additional.support.content': 'Actualizare conținut',
    'services.additional.support.tech': 'Suport tehnic',
    'services.additional.support.monitoring': 'Monitorizare securitate',
    'services.additional.seo.title': 'Promovare SEO',
    'services.additional.seo.desc': 'Promovare profesională SEO a site-ului dvs. în motoarele de căutare. Efectuăm analiză a concurenților, optimizăm conținutul și configurăm structura link-urilor pentru îmbunătățirea pozițiilor.',
    'services.additional.seo.price': '€200/lună',
    'services.additional.seo.analysis': 'Analiză concurenți',
    'services.additional.seo.optimization': 'Optimizare conținut',
    'services.additional.seo.links': 'Lucru cu link-uri',
    'services.additional.ads.title': 'Publicitate contextuală',
    'services.additional.ads.desc': 'Configurare și gestionare a publicității contextuale pentru atragerea audienței țintă. Lucrăm cu Google Ads și Facebook Ads, oferim analitică detaliată și rapoarte.',
    'services.additional.ads.price': '€150/lună',
    'services.additional.ads.google': 'Configurare Google Ads',
    'services.additional.ads.facebook': 'Facebook Ads',
    'services.additional.ads.analytics': 'Analitică și rapoarte',
    'services.additional.more': 'Află mai multe',
    'services.additional.title': 'Servicii suplimentare',
    'services.additional.subtitle': 'Extinde posibilitățile site-ului tău',
    'services.category.websites': 'Site-uri Web',
    'services.category.telegram': 'Boti Telegram',
    'services.category.automation': 'Automatizare',
    'services.category.mobile': 'Aplicații Mobile',

    // Mobile Packages RO
    'services.mobile.mvp': 'Scale MVP',
    'services.mobile.mvp.desc': 'Verificarea rapidă a ipotezelor. Creăm o aplicație funcțională care rulează pe Android, iOS și Web simultan.',
    'services.mobile.business': 'Business App',
    'services.mobile.business.desc': 'Un instrument puternic pentru brandul tău. Lansare completă în App Store și Google Play cu notificări Push.',
    'services.mobile.shop': 'M-Commerce',
    'services.mobile.shop.desc': 'Magazinul tău în buzunarul clientului. Comoditate maximă la cumpărare cu integrare Apple Pay și Google Pay.',

    'services.time.mobile.mvp': '14-21 zile',
    'services.time.mobile.business': '30-45 zile',
    'services.time.mobile.shop': '45-60 zile',

    'services.features.mobile.mvp.hybrid': 'Android + iOS + Web',
    'services.features.mobile.mvp.auth': 'Autorizare și profil',
    'services.features.mobile.mvp.adaptive': 'Design UI/UX adaptiv',
    'services.features.mobile.business.stores': 'Publicare în App Store / Google Play',
    'services.features.mobile.business.push': 'Notificări Push',
    'services.features.mobile.business.native': 'Acces la funcțiile smartphone-ului',
    'services.features.mobile.shop.pay': 'Apple Pay / Google Play',
    'services.features.mobile.shop.ota': 'Actualizări instantanee (OTA)',
    'services.features.mobile.shop.offline': 'Lucru în mod offline',

    // Telegram Packages RO
    'services.tg.basic': 'Bot de vizită',
    'services.tg.basic.desc': 'Ideal pentru prezentarea serviciilor, programarea clienților și răspunsuri la întrebări frecvente în messenger.',
    'services.tg.shop': 'Magazin în Telegram',
    'services.tg.shop.desc': 'Vânzări complete în interiorul Telegram. Catalog, coș și acceptarea plăților fără a părăsi aplicația.',
    'services.tg.complex': 'Sisteme complexe',
    'services.tg.complex.desc': 'Soluții individuale: integrare cu API, automatizarea administrării canalelor și grupurilor.',

    'services.time.tg.basic': '3-5 zile',
    'services.time.tg.shop': '7-14 zile',
    'services.time.tg.complex': 'de la 10 zile',

    'services.features.tg.basic.menu': 'Meniu interactiv',
    'services.features.tg.basic.faq': 'Răspunsuri la FAQ',
    'services.features.tg.basic.form': 'Colectare cereri',
    'services.features.tg.basic.admin': 'Panou admin simplificat',
    'services.features.tg.basic.broadcast': 'Mesaje în masă',
    'services.features.tg.basic.stats': 'Statistici utilizatori',
    'services.features.tg.shop.catalog': 'Catalog produse',
    'services.features.tg.shop.cart': 'Coș și checkout',
    'services.features.tg.shop.payments': 'Acceptare plăți',
    'services.features.tg.shop.notification': 'Notificări comenzi',
    'services.features.tg.shop.ref': 'Sistem de recomandări (MGM)',
    'services.features.tg.shop.sheets': 'Integrare cu Google Sheets',
    'services.features.tg.complex.api': 'Integrare API extern',
    'services.features.tg.complex.db': 'Bază de date utilizatori',
    'services.features.tg.complex.custom': 'Logică individuală',
    'services.features.tg.complex.ai': 'Integrare cu AI (ChatGPT)',
    'services.features.tg.complex.subs': 'Sistem de abonamente plătite',

    // Automation Packages RO
    'services.auto.parsing': 'Parsing date',
    'services.auto.parsing.desc': 'Colectarea automată a informațiilor de pe orice site-uri și marketplace-uri în format convenabil (Excel/JSON).',
    'services.auto.scripts': 'Scripturi personalizate',
    'services.auto.scripts.desc': 'Dezvoltarea scripturilor pentru automatizarea sarcinilor de rutină, procesarea fișierelor și administrarea sistemelor.',
    'services.auto.complex': 'Smart Platform',
    'services.auto.complex.desc': 'Platformă web cu integrare profundă a instrumentelor de automatizare, parsing și AI.',

    'services.time.auto.parsing': '3-5 zile',
    'services.time.auto.scripts': 'de la 3 zile',
    'services.time.auto.complex': 'de la 14 zile',

    'services.features.auto.parsing.sites': 'Colectare de pe orice site',
    'services.features.auto.parsing.format': 'Format export convenabil',
    'services.features.auto.parsing.schedule': 'Rulare programată',
    'services.features.auto.parsing.stealth': 'Protecție împotriva blocării (Proxy)',
    'services.features.auto.scripts.routine': 'Automatizare rutină',
    'services.features.auto.scripts.clean': 'Cod curat și clar',
    'services.features.auto.scripts.support': 'Mentenanță și suport',
    'services.features.auto.scripts.secure': 'Criptare securizată a datelor',
    'services.features.auto.scripts.docs': 'Instrucțiuni și documentație',
    'services.features.auto.complex.web': 'Interfață web de gestionare',
    'services.features.auto.complex.parsing': 'Parsing de date integrat',
    'services.features.auto.complex.scripts': 'Automatizarea proceselor de afaceri',
    'services.features.auto.complex.ai': 'Integrare cu AI (GPT-4/Claude)',
    'services.features.auto.complex.notif': 'Sistem de notificări',

    'services.cta.title': 'Nu ai găsit pachetul potrivit?',
    'services.cta.subtitle': 'Vom crea o ofertă personalizată pentru nevoile și bugetul tău',
    'services.cta.button': 'Obține consultație',

    // Features
    'features.tech': 'Stiva tehnologică',
    'features.tech.desc': 'Utilizăm instrumente avansate: React, Next.js, Python și rețele neuronale.',
    'features.business': 'Rezultat de business',
    'features.business.desc': 'Ne concentrăm pe obiectivele afacerii tale și pe randamentul investițiilor (ROI).',
    'features.ai': 'Inovații AI',
    'features.ai.desc': 'Implementăm inteligența artificială pentru automatizarea proceselor de rutină.',
    'features.support': 'Parteneriat 24/7',
    'features.support.desc': 'Însoțim proiectul tău în toate etapele: de la idee la scalare.',

    // Portfolio
    'portfolio.title': 'Lucrările noastre',
    'portfolio.subtitle': 'Exemple de proiecte realizate cu succes',
    'portfolio.all': 'Toate',
    'portfolio.landing': 'Landing Pages',
    'portfolio.business': 'Site-uri vizită',
    'portfolio.shop': 'Magazine',
    'portfolio.problem': 'Problemă',
    'portfolio.solution': 'Soluție',
    'portfolio.result': 'Rezultat',
    'portfolio.view': 'Vezi proiectul',
    'portfolio.back': 'Înapoi la portofoliu',

    // Blog
    'blog.title': 'Blog',
    'blog.subtitle': 'Articole utile despre crearea și promovarea site-urilor',
    'blog.readMore': 'Citește mai mult',
    'blog.readTime': 'min citire',
    'blog.back': 'Înapoi la blog',

    // Contact
    'contact.title': 'Contactează-ne',
    'contact.subtitle': 'Pregătit să discutăm proiectul tău? Lasă o cerere și te vom contacta în curând',
    'contact.name': 'Numele tău',
    'contact.email': 'Email',
    'contact.phone': 'Telefon',
    'contact.message': 'Mesaj',
    'contact.projectType': 'Tipul proiectului',
    'contact.send': 'Trimite cererea',
    'contact.sending': 'Se trimite...',
    'contact.success': 'Mulțumim! Te vom contacta în curând.',
    'contact.error': 'A apărut o eroare. Încearcă mai târziu.',
    'contact.phone.label': 'Telefon',
    'contact.email.label': 'Email',
    'contact.address.label': 'Adresă',
    'contact.address.value': 'Chișinău, str. Pușkin 22',
    'contact.quick.title': 'Contact rapid',
    'contact.quick.write': 'Scrie un mesaj',
    'contact.hours.title': 'Program de lucru',
    'contact.hours.weekdays': 'Lun - Vin',
    'contact.hours.weekdays.time': '09:00 - 18:00',
    'contact.hours.saturday': 'Sâmbătă',
    'contact.hours.saturday.time': '10:00 - 15:00',
    'contact.hours.sunday': 'Duminică',
    'contact.hours.sunday.time': 'Zi liberă',
    'contact.faq.title': 'Întrebări frecvente',
    'contact.faq.q1': 'Cât timp durează crearea unui site?',
    'contact.faq.a1': 'Landing page - 7-10 zile, site vizită - 14-21 zile, magazin online - 30-45 zile.',
    'contact.faq.q2': 'Care este forma de plată?',
    'contact.faq.a2': 'Preplată 50% pentru începerea lucrărilor, 50% după predarea proiectului. Posibilă rată.',
    'contact.faq.q3': 'Este inclus suportul tehnic?',
    'contact.faq.a3': 'Da, suport sub garanție de la 1 la 6 luni în funcție de pachet.',
    'contact.faq.q4': 'Pot edita conținutul singur?',
    'contact.faq.a4': 'Da, oferim panou CMS și instruire pentru lucrul cu el.',
    'contact.form.title': 'Lasă o cerere',

    // Portfolio
    'portfolio.project.beauty.title': 'Beauty Salon Premium',
    'portfolio.project.beauty.category': 'Salon de frumusețe',
    'portfolio.project.beauty.problem': 'Salonul pierdea clienți din cauza lipsei rezervărilor online',
    'portfolio.project.beauty.solution': 'Am creat un landing page cu formular de rezervare și integrare WhatsApp',
    'portfolio.project.beauty.result': '+150% rezervări online în prima lună',
    'portfolio.project.tech.title': 'TechStore Moldova',
    'portfolio.project.tech.category': 'Electronică',
    'portfolio.project.tech.problem': 'Conversie scăzută a vânzărilor online',
    'portfolio.project.tech.solution': 'Am dezvoltat un magazin online intuitiv cu plată rapidă',
    'portfolio.project.tech.result': '+200% vânzări online, cecul mediu a crescut cu 40%',
    'portfolio.project.law.title': 'Law Firm Pro',
    'portfolio.project.law.category': 'Servicii juridice',
    'portfolio.project.law.problem': 'Site-ul învechit nu atrăgea clienți noi',
    'portfolio.project.law.solution': 'Am creat un site corporativ modern cu blog',
    'portfolio.project.law.result': '+85% cereri primite, îmbunătățirea imaginii companiei',
    'portfolio.project.fitness.title': 'Fitness Club Launch',
    'portfolio.project.fitness.category': 'Club de fitness',
    'portfolio.project.fitness.problem': 'Clubul nou avea nevoie de atragere rapidă a membrilor',
    'portfolio.project.fitness.solution': 'Landing page strălucitor cu promoții și înregistrare online',
    'portfolio.project.fitness.result': '300+ membri noi în 2 luni',
    'portfolio.project.fashion.title': 'Fashion Boutique',
    'portfolio.project.fashion.category': 'Modă',
    'portfolio.project.fashion.problem': 'Boutique-ul dorea să intre în vânzările online',
    'portfolio.project.fashion.solution': 'Magazin online elegant de îmbrăcăminte cu probă AR',
    'portfolio.project.fashion.result': '€50K+ cifră de afaceri în primele 3 luni',
    'portfolio.project.restaurant.title': 'Restaurant Chain',
    'portfolio.project.restaurant.category': 'Business restaurant',
    'portfolio.project.restaurant.problem': 'Lanțul de restaurante avea nevoie de o platformă unificată',
    'portfolio.project.restaurant.solution': 'Site multifuncțional cu comandă online și rezervare',
    'portfolio.project.restaurant.result': '+120% comenzi online, economie la call-center',
    'portfolio.project.mded.title': 'Ajutor de Stat MDED',
    'portfolio.project.mded.category': 'Proiect guvernamental',
    'portfolio.project.mded.problem': 'Era necesar un portal informativ modern despre programul de sprijin de stat pentru investițiile industriale',
    'portfolio.project.mded.solution': 'Landing multilingv pe WordPress cu ACF, Timber și Twig. Design modern, layout adaptiv, navigare intuitivă',
    'portfolio.project.mded.result': 'Prezentare profesională a informațiilor despre program, UX îmbunătățit pentru cetățeni și investitori',

    // Blog
    'blog.categories.all': 'Toate articolele',
    'blog.categories.prices': 'Prețuri',
    'blog.categories.tips': 'Sfaturi',
    'blog.categories.seo': 'SEO',
    'blog.categories.design': 'Design',
    'blog.categories.ecommerce': 'E-commerce',
    'blog.article1.title': 'Cât costă crearea unui site în Moldova în 2025',
    'blog.article1.excerpt': 'Analiză detaliată a prețurilor pentru dezvoltarea site-urilor: de la landing pages la magazine online. Ce influențează costul și cum să nu plătești în plus.',
    'blog.article1.category': 'Prețuri',
    'blog.article2.title': '10 greșeli la crearea unui site pentru afacere',
    'blog.article2.excerpt': 'Greșeli tipice pe care le fac antreprenorii la comandarea unui site. Cum să le eviți și să economisești bani.',
    'blog.article2.category': 'Sfaturi',
    'blog.article3.title': 'Landing page sau magazin online: ce să alegi pentru start',
    'blog.article3.excerpt': 'Comparație a tipurilor de site-uri pentru afaceri mici. Când ai nevoie de landing page și când merită să faci imediat magazin.',
    'blog.article3.category': 'Sfaturi',
    'blog.article4.title': 'Optimizare SEO site: ghid pentru începători',
    'blog.article4.excerpt': 'Principii de bază SEO pe care ar trebui să le cunoască fiecare proprietar de site. Cum să urci în top Google fără bugete mari.',
    'blog.article4.category': 'SEO',
    'blog.article5.title': 'Design responsive: de ce este critic în 2025',
    'blog.article5.excerpt': 'Statistici trafic mobil în Moldova și de ce site-ul tău ar trebui să funcționeze perfect pe smartphone-uri.',
    'blog.article5.category': 'Design',
    'blog.article6.title': 'Integrare sisteme de plată pentru magazin online',
    'blog.article6.excerpt': 'Prezentare generală a sistemelor de plată populare în Moldova: comisioane, caracteristici de conectare și securitate.',
    'blog.article6.category': 'E-commerce',
    'blog.recommended': 'Recomandăm',
    'blog.newsletter.title': 'Primește articole noi',
    'blog.newsletter.title.prefix': 'Primește ',
    'blog.newsletter.title.highlight': 'articole noi',
    'blog.newsletter.subtitle': 'Abonează-te la newsletter și află primul despre materialele noi',
    'blog.newsletter.email': 'Email-ul tău',
    'blog.newsletter.subscribe': 'Abonează-te',
    'blog.newsletter.success': 'Mulțumim pentru abonare! Te vom contacta când va apărea un articol nou.',
    'blog.newsletter.error': 'A apărut o eroare. Încearcă mai târziu.',
    'blog.newsletter.exists': 'Ești deja abonat!',
    'blog.newsletter.sending': 'Se trimite...',

    // Home
    'home.hero.badge': '�️ Soluții IT de înaltă tehnologie pentru afaceri',
    'home.why.title': 'De ce ne aleg',
    'home.why.highlight': 'WebPoint',
    'home.why.subtitle': 'Implementăm tehnologii avansate și automatizare pentru ca afacerea ta să crească mai rapid și să funcționeze mai eficient.',
    'home.stats.title_suffix': 'în cifre',
    'home.stats.subtitle': 'Indicatori reali ai experienței și încrederii clienților',
    'home.services.title': 'Serviciile noastre',
    'home.services.subtitle': 'Alege soluția potrivită pentru afacerea ta',
    'home.services.popular': 'Popular',
    'home.cta.title': 'Gata să începi',
    'home.cta.highlight': 'proiectul tău?',
    'home.cta.subtitle': 'Contactează-ne astăzi și obține o consultație gratuită pentru proiectul tău',

    // NotFound
    'notfound.title': 'Pagină negăsită',
    'notfound.subtitle': 'Din păcate, pagina solicitată nu există sau a fost mutată.',
    'notfound.button': 'Înapoi la pagina principală',

    // Footer
    'footer.about': 'Despre companie',
    'footer.about.text': 'Creăm soluții IT de înaltă tehnologie și sisteme digitale pentru afaceri din întreaga lume',
    'footer.services': 'Servicii',
    'footer.contact': 'Contacte',
    'footer.social': 'Rețele sociale',
    'footer.rights': 'Toate drepturile rezervate',

    // Project Detail
    'projectDetail.category': 'Categorie',
    'projectDetail.type': 'Tipul proiectului',
    'projectDetail.client': 'Client',
    'projectDetail.date': 'Data',
    'projectDetail.technologies': 'Tehnologii',

    // Admin Portfolio
    'admin.portfolio.category': 'Categorie',
    'admin.portfolio.type': 'Tipul proiectului',
    'admin.portfolio.typeLabel': 'Tip',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'home.services.web.title': 'Web Solutions',
    'home.services.web.desc': 'We create modern websites and scalable platforms of any complexity.',
    'home.services.tg.title': 'Telegram Systems',
    'home.services.tg.desc': 'We develop ecosystems in the messenger: from bots to Mini Apps.',
    'home.services.auto.title': 'AI & Automation',
    'home.services.auto.desc': 'We implement AI and automate routine, freeing up time for growth.',
    'home.services.mobile.title': 'Mobile Development',
    'home.services.mobile.desc': 'We create fast and intuitive apps for iOS and Android.',

    // Hero
    'hero.title': 'Development of high-tech',
    'hero.highlight': 'IT solutions',
    'hero.subtitle': 'We create effective digital products for business: from corporate websites to mobile apps, Telegram ecosystems, and AI automation.',
    'hero.cta': 'Get a quote',
    'hero.consultation': 'Free consultation',

    // About
    'about.title': 'About us',
    'about.subtitle': 'WebPoint is a team of professionals creating modern web solutions for your business',
    'about.experience': 'Years of experience',
    'about.projects': 'Projects',
    'about.clients': 'Satisfied clients',

    // Services
    'services.title': 'Our services',
    'services.subtitle': 'Choose the right solution for your business',
    'services.landing': 'Landing Page',
    'services.landing.desc': 'Converting single-page website to attract customers and increase conversions',
    'services.business': 'Business Website',
    'services.business.desc': 'Multi-page corporate website with complete information about your company',
    'services.shop': 'Online Store',
    'services.shop.desc': 'Full-featured online store with catalog, shopping cart and payment system',
    'services.from': 'from',
    'services.order': 'Order',
    'services.time.landing': '7-10 days',
    'services.time.business': '14-21 days',
    'services.time.shop': '30-45 days',
    'services.duration': 'Duration',
    'services.popular.badge': 'Popular choice',
    'services.features.landing.design': 'Modern design',
    'services.features.landing.responsive': 'Responsive design',
    'services.features.landing.seo': 'SEO optimization',
    'services.features.landing.form': 'Contact form',
    'services.features.business.pages': 'Up to 10 pages',
    'services.features.business.cms': 'CMS admin panel',
    'services.features.business.social': 'Social media integration',
    'services.features.business.analytics': 'Analytics',
    'services.features.shop.catalog': 'Product catalog',
    'services.features.shop.cart': 'Shopping cart & payment',
    'services.features.shop.account': 'Personal account',
    'services.features.shop.delivery': 'Delivery integration',
    'services.features.landing.full.design': 'Unique modern design',
    'services.features.landing.full.responsive': 'Responsive design for all devices',
    'services.features.landing.full.seo': 'SEO optimization and meta tags setup',
    'services.features.landing.full.form': 'Contact form with email notifications',
    'services.features.landing.full.analytics': 'Google Analytics integration',
    'services.features.landing.full.hosting': 'Hosting and domain setup',
    'services.features.landing.full.support': '1 month technical support',
    'services.features.landing.full.training': 'Content management training',
    'services.features.business.full.pages': 'Up to 10 informational pages',
    'services.features.business.full.design': 'Unique design for your brand',
    'services.features.business.full.cms': 'Administrative panel (CMS)',
    'services.features.business.full.contact': 'Contact form',
    'services.features.business.full.social': 'Social media integration',
    'services.features.business.full.blog': 'Blog or news section',
    'services.features.business.full.multilang': 'Multilingual (RU/RO)',
    'services.features.business.full.maps': 'Google Maps integration',
    'services.features.business.full.seo': 'SEO optimization for all pages',
    'services.features.business.full.support': '3 months technical support',
    'services.features.shop.full.catalog': 'Product catalog with filtering',
    'services.features.shop.full.cart': 'Shopping cart and checkout',
    'services.features.shop.full.payment': 'Payment systems integration',
    'services.features.shop.full.account': 'Customer personal account',
    'services.features.shop.full.admin': 'Administrative control panel',
    'services.features.shop.full.discounts': 'Discounts and promo codes system',
    'services.features.shop.full.delivery': 'Delivery services integration',
    'services.features.shop.full.notifications': 'Email notifications for orders',
    'services.features.shop.full.reviews': 'Product reviews and ratings',
    'services.features.shop.full.multilang': 'Multilingual and multi-currency',
    'services.features.shop.full.seo': 'Product SEO optimization',
    'services.features.shop.full.support': '6 months technical support',
    'services.additional.support.title': 'Support and development',
    'services.additional.support.desc': 'Comprehensive maintenance and development of your website. We provide regular content updates, technical support, and security monitoring.',
    'services.additional.support.price': '€50/month',
    'services.additional.support.content': 'Content updates',
    'services.additional.support.tech': 'Technical support',
    'services.additional.support.monitoring': 'Security monitoring',
    'services.additional.seo.title': 'SEO promotion',
    'services.additional.seo.desc': 'Professional SEO promotion of your website in search engines. We conduct competitor analysis, optimize content, and configure link structure to improve rankings.',
    'services.additional.seo.price': '€200/month',
    'services.additional.seo.analysis': 'Competitor analysis',
    'services.additional.seo.optimization': 'Content optimization',
    'services.additional.seo.links': 'Link building',
    'services.additional.ads.title': 'Contextual advertising',
    'services.additional.ads.desc': 'Setup and management of contextual advertising to attract target audience. We work with Google Ads and Facebook Ads, provide detailed analytics and reports.',
    'services.additional.ads.price': '€150/month',
    'services.additional.ads.google': 'Google Ads setup',
    'services.additional.ads.facebook': 'Facebook Ads',
    'services.additional.ads.analytics': 'Analytics and reports',
    'services.additional.more': 'Learn more',
    'services.additional.title': 'Additional services',
    'services.additional.subtitle': 'Expand your website capabilities',
    'services.category.websites': 'Websites',
    'services.category.telegram': 'Telegram Bots',
    'services.category.automation': 'Automation',
    'services.category.mobile': 'Mobile Apps',

    // Mobile Packages EN
    'services.mobile.mvp': 'Scale MVP',
    'services.mobile.mvp.desc': 'Fast hypothesis testing. We build a functional app that works on Android, iOS, and Web simultaneously.',
    'services.mobile.business': 'Business App',
    'services.mobile.business.desc': 'A powerful tool for your brand. Full launch in App Store and Google Play with Push notifications.',
    'services.mobile.shop': 'M-Commerce',
    'services.mobile.shop.desc': 'Your store in the client\'s pocket. Maximum shopping convenience with Apple Pay and Google Pay integration.',

    'services.time.mobile.mvp': '14-21 days',
    'services.time.mobile.business': '30-45 days',
    'services.time.mobile.shop': '45-60 days',

    'services.features.mobile.mvp.hybrid': 'Android + iOS + Web',
    'services.features.mobile.mvp.auth': 'Auth & Profile',
    'services.features.mobile.mvp.adaptive': 'Adaptive UI/UX Design',
    'services.features.mobile.mvp.social': 'Social media registration',
    'services.features.mobile.mvp.analytics': 'Basic analytics (Firebase)',
    'services.features.mobile.business.stores': 'App Store / Google Play Publishing',
    'services.features.mobile.business.push': 'Push Notifications',
    'services.features.mobile.business.native': 'Native Device Features Access',
    'services.features.mobile.business.offline': 'Offline data storage',
    'services.features.mobile.business.geo': 'Geolocation and maps',
    'services.features.mobile.shop.pay': 'Apple Pay / Google Pay',
    'services.features.mobile.shop.ota': 'Over-the-Air Updates (OTA)',
    'services.features.mobile.shop.offline': 'Offline Mode Support',
    'services.features.mobile.shop.search': 'Smart search and filters',
    'services.features.mobile.shop.history': 'Order history and statuses',

    // Telegram Packages EN
    'services.tg.basic': 'Business Card Bot',
    'services.tg.basic.desc': 'Perfect for presenting services, booking clients, and answering FAQs within the messenger.',
    'services.tg.shop': 'Telegram Shop',
    'services.tg.shop.desc': 'Full-featured sales inside Telegram. Catalog, shopping cart, and payments without leaving the app.',
    'services.tg.complex': 'Complex Systems',
    'services.tg.complex.desc': 'Custom solutions: API integration, channel and group administration automation.',

    'services.time.tg.basic': '3-5 days',
    'services.time.tg.shop': '7-14 days',
    'services.time.tg.complex': 'from 10 days',

    'services.features.tg.basic.menu': 'Interactive menu',
    'services.features.tg.basic.faq': 'FAQ automation',
    'services.features.tg.basic.form': 'Lead generation form',
    'services.features.tg.basic.admin': 'Mini admin panel',
    'services.features.tg.basic.broadcast': 'Broadcast messaging',
    'services.features.tg.basic.stats': 'User statistics',
    'services.features.tg.shop.catalog': 'Product catalog',
    'services.features.tg.shop.cart': 'Cart and checkout',
    'services.features.tg.shop.payments': 'Payment integration',
    'services.features.tg.shop.notification': 'Order notifications',
    'services.features.tg.shop.ref': 'Referral system (MGM)',
    'services.features.tg.shop.sheets': 'Google Sheets integration',
    'services.features.tg.complex.api': 'External API integration',
    'services.features.tg.complex.db': 'User database',
    'services.features.tg.complex.custom': 'Custom business logic',
    'services.features.tg.complex.ai': 'AI integration (ChatGPT)',
    'services.features.tg.complex.subs': 'Paid subscription system',

    // Automation Packages EN
    'services.auto.parsing': 'Data Parsing',
    'services.auto.parsing.desc': 'Automated information collection from any websites and marketplaces in a convenient format (Excel/JSON).',
    'services.auto.scripts': 'Custom Scripts',
    'services.auto.scripts.desc': 'Development of scripts for automating routine tasks, file processing, and system administration.',
    'services.auto.complex': 'Smart Platform',
    'services.auto.complex.desc': 'Web platform with deep integration of automation, data parsing and AI tools.',

    'services.time.auto.parsing': '3-5 days',
    'services.time.auto.scripts': 'from 3 days',
    'services.time.auto.complex': 'from 14 days',

    'services.features.auto.parsing.sites': 'Data collection from any site',
    'services.features.auto.parsing.format': 'Convenient export format',
    'services.features.auto.parsing.schedule': 'Scheduled execution',
    'services.features.auto.parsing.stealth': 'Anti-blocking protection (Proxy)',
    'services.features.auto.scripts.routine': 'Routine automation',
    'services.features.auto.scripts.clean': 'Clean and documented code',
    'services.features.auto.scripts.support': 'Maintenance and support',
    'services.features.auto.scripts.secure': 'Secure data encryption',
    'services.features.auto.scripts.docs': 'Instructions and documentation',
    'services.features.auto.complex.web': 'Management Web Interface',
    'services.features.auto.complex.parsing': 'Built-in Data Parsing',
    'services.features.auto.complex.scripts': 'Business Process Automation',
    'services.features.auto.complex.ai': 'AI Integration (GPT-4/Claude)',
    'services.features.auto.complex.notif': 'Notification System',

    'services.cta.title': 'Didn\'t find the right package?',
    'services.cta.subtitle': 'We will create a custom offer for your needs and budget',
    'services.cta.button': 'Get consultation',

    // Features
    'features.tech': 'Technology Stack',
    'features.tech.desc': 'We use advanced tools: React, Next.js, Python, and neural networks.',
    'features.business': 'Business Result',
    'features.business.desc': 'We focus on your business goals and return on investment (ROI).',
    'features.ai': 'AI Innovations',
    'features.ai.desc': 'We implement artificial intelligence to automate routine processes.',
    'features.support': '24/7 Partnership',
    'features.support.desc': 'We accompany your project at all stages: from idea to scaling.',

    // Portfolio
    'portfolio.title': 'Our works',
    'portfolio.subtitle': 'Examples of successfully completed projects',
    'portfolio.all': 'All',
    'portfolio.landing': 'Landing Pages',
    'portfolio.business': 'Business Websites',
    'portfolio.shop': 'Stores',
    'portfolio.problem': 'Problem',
    'portfolio.solution': 'Solution',
    'portfolio.result': 'Result',
    'portfolio.view': 'View project',
    'portfolio.back': 'Back to portfolio',

    // Blog
    'blog.title': 'Blog',
    'blog.subtitle': 'Useful articles about website creation and promotion',
    'blog.readMore': 'Read more',
    'blog.readTime': 'min read',
    'blog.back': 'Back to blog',

    // Contact
    'contact.title': 'Contact us',
    'contact.subtitle': 'Ready to discuss your project? Leave a request and we will contact you shortly',
    'contact.name': 'Your name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.message': 'Message',
    'contact.projectType': 'Project type',
    'contact.send': 'Send request',
    'contact.sending': 'Sending...',
    'contact.success': 'Thank you! We will contact you shortly.',
    'contact.error': 'An error occurred. Please try again later.',
    'contact.phone.label': 'Phone',
    'contact.email.label': 'Email',
    'contact.address.label': 'Address',
    'contact.address.value': 'Chisinau, Pushkin St. 22',
    'contact.quick.title': 'Quick contact',
    'contact.quick.write': 'Send message',
    'contact.hours.title': 'Working hours',
    'contact.hours.weekdays': 'Mon - Fri',
    'contact.hours.weekdays.time': '09:00 - 18:00',
    'contact.hours.saturday': 'Saturday',
    'contact.hours.saturday.time': '10:00 - 15:00',
    'contact.hours.sunday': 'Sunday',
    'contact.hours.sunday.time': 'Day off',
    'contact.faq.title': 'Frequently asked questions',
    'contact.faq.q1': 'How long does it take to create a website?',
    'contact.faq.a1': 'Landing page - 7-10 days, business website - 14-21 days, online store - 30-45 days.',
    'contact.faq.q2': 'What is the payment method?',
    'contact.faq.a2': '50% prepayment to start work, 50% after project delivery. Installment plan available.',
    'contact.faq.q3': 'Is technical support included?',
    'contact.faq.a3': 'Yes, warranty support from 1 to 6 months depending on the package.',
    'contact.faq.q4': 'Can I edit content myself?',
    'contact.faq.a4': 'Yes, we provide a CMS panel and train you to work with it.',
    'contact.form.title': 'Leave a request',

    // Portfolio
    'portfolio.project.beauty.title': 'Beauty Salon Premium',
    'portfolio.project.beauty.category': 'Beauty salon',
    'portfolio.project.beauty.problem': 'Salon was losing clients due to lack of online booking',
    'portfolio.project.beauty.solution': 'Created a landing page with booking form and WhatsApp integration',
    'portfolio.project.beauty.result': '+150% online bookings in the first month',
    'portfolio.project.tech.title': 'TechStore Moldova',
    'portfolio.project.tech.category': 'Electronics',
    'portfolio.project.tech.problem': 'Low online sales conversion',
    'portfolio.project.tech.solution': 'Developed an intuitive online store with fast payment',
    'portfolio.project.tech.result': '+200% online sales, average order value increased by 40%',
    'portfolio.project.law.title': 'Law Firm Pro',
    'portfolio.project.law.category': 'Legal services',
    'portfolio.project.law.problem': 'Outdated website did not attract new clients',
    'portfolio.project.law.solution': 'Created a modern corporate website with blog',
    'portfolio.project.law.result': '+85% incoming requests, improved company image',
    'portfolio.project.fitness.title': 'Fitness Club Launch',
    'portfolio.project.fitness.category': 'Fitness club',
    'portfolio.project.fitness.problem': 'New club needed quick member acquisition',
    'portfolio.project.fitness.solution': 'Bright landing page with promotions and online registration',
    'portfolio.project.fitness.result': '300+ new members in 2 months',
    'portfolio.project.fashion.title': 'Fashion Boutique',
    'portfolio.project.fashion.category': 'Fashion',
    'portfolio.project.fashion.problem': 'Boutique wanted to enter online sales',
    'portfolio.project.fashion.solution': 'Elegant online clothing store with AR try-on',
    'portfolio.project.fashion.result': '€50K+ turnover in the first 3 months',
    'portfolio.project.restaurant.title': 'Restaurant Chain',
    'portfolio.project.restaurant.category': 'Restaurant business',
    'portfolio.project.restaurant.problem': 'Restaurant chain needed a unified platform',
    'portfolio.project.restaurant.solution': 'Multifunctional website with online ordering and booking',
    'portfolio.project.restaurant.result': '+120% online orders, savings on call center',
    'portfolio.project.mded.title': 'State Aid MDED',
    'portfolio.project.mded.category': 'Government project',
    'portfolio.project.mded.problem': 'A modern information portal was needed about the state support program for industrial investments',
    'portfolio.project.mded.solution': 'Multilingual landing page on WordPress with ACF, Timber and Twig. Modern design, responsive layout, intuitive navigation',
    'portfolio.project.mded.result': 'Professional presentation of program information, improved UX for citizens and investors',

    // Blog
    'blog.categories.all': 'All articles',
    'blog.categories.prices': 'Prices',
    'blog.categories.tips': 'Tips',
    'blog.categories.seo': 'SEO',
    'blog.categories.design': 'Design',
    'blog.categories.ecommerce': 'E-commerce',
    'blog.article1.title': 'How much does website creation cost in Moldova in 2025',
    'blog.article1.excerpt': 'Detailed breakdown of website development prices: from landing pages to online stores. What affects the cost and how not to overpay.',
    'blog.article1.category': 'Prices',
    'blog.article2.title': '10 mistakes when creating a website for business',
    'blog.article2.excerpt': 'Typical mistakes entrepreneurs make when ordering a website. How to avoid them and save money.',
    'blog.article2.category': 'Tips',
    'blog.article3.title': 'Landing page or online store: what to choose for startup',
    'blog.article3.excerpt': 'Comparison of website types for small businesses. When you need a landing page and when it\'s worth making a store right away.',
    'blog.article3.category': 'Tips',
    'blog.article4.title': 'Website SEO optimization: guide for beginners',
    'blog.article4.excerpt': 'Basic SEO principles every website owner should know. How to get to the top of Google without big budgets.',
    'blog.article4.category': 'SEO',
    'blog.article5.title': 'Responsive design: why it\'s critical in 2025',
    'blog.article5.excerpt': 'Mobile traffic statistics in Moldova and why your website should work perfectly on smartphones.',
    'blog.article5.category': 'Design',
    'blog.article6.title': 'Payment systems integration for online store',
    'blog.article6.excerpt': 'Overview of popular payment systems in Moldova: fees, connection features and security.',
    'blog.article6.category': 'E-commerce',
    'blog.recommended': 'Recommended',
    'blog.newsletter.title': 'Get new articles',
    'blog.newsletter.title.prefix': 'Get ',
    'blog.newsletter.title.highlight': 'new articles',
    'blog.newsletter.subtitle': 'Subscribe to newsletter and be the first to know about new materials',
    'blog.newsletter.email': 'Your email',
    'blog.newsletter.subscribe': 'Subscribe',
    'blog.newsletter.success': 'Thanks for subscribing! We will contact you when a new article is released.',
    'blog.newsletter.error': 'An error occurred. Please try again later.',
    'blog.newsletter.exists': 'You are already subscribed!',
    'blog.newsletter.sending': 'Sending...',

    // Home
    'home.hero.badge': '�️ High-tech IT solutions for business',
    'home.why.title': 'Why choose',
    'home.why.highlight': 'WebPoint',
    'home.why.subtitle': 'We implement advanced technologies and automation so that your business grows faster and works more effectively.',
    'home.stats.title_suffix': 'in numbers',
    'home.stats.subtitle': 'Real indicators of our experience and client trust',
    'home.services.title': 'Our services',
    'home.services.subtitle': 'Choose the right solution for your business',
    'home.services.popular': 'Popular',
    'home.cta.title': 'Ready to start',
    'home.cta.highlight': 'your project?',
    'home.cta.subtitle': 'Contact us today and get a free consultation for your project',

    // NotFound
    'notfound.title': 'Page not found',
    'notfound.subtitle': 'Unfortunately, the requested page does not exist or has been moved.',
    'notfound.button': 'Back to home',

    // Footer
    'footer.about': 'About company',
    'footer.about.text': 'We create high-tech IT solutions and digital systems for businesses worldwide',
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.social': 'Social networks',
    'footer.rights': 'All rights reserved',

    // Project Detail
    'projectDetail.category': 'Category',
    'projectDetail.type': 'Project Type',
    'projectDetail.client': 'Client',
    'projectDetail.date': 'Date',
    'projectDetail.technologies': 'Technologies',

    // Admin Portfolio
    'admin.portfolio.category': 'Category',
    'admin.portfolio.type': 'Project Type',
    'admin.portfolio.typeLabel': 'Type',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'webpoint-language';

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  // Загружаем язык из localStorage при инициализации
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY) as Language;
      if (savedLanguage && (savedLanguage === 'ru' || savedLanguage === 'ro' || savedLanguage === 'en')) {
        return savedLanguage;
      }
    }
    return 'ru';
  });

  // Сохраняем язык в localStorage при изменении
  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    }
  }, [language]);

  // Обертка для setLanguage, чтобы сохранять в localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const langTranslations = translations[language];
    return (langTranslations[key as keyof typeof langTranslations] as string) || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
